### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl' on Windows

### ISSUE THREAD

**Issue by CT83** [Netflix/metaflow#10]
### Steps to Reproduce
1. `pip install metaflow`
2. `metaflow`

```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Code\Python\CT83-PC\venv\metaflow\Scripts\metaflow.exe\__main__.py", line 5, in <module>
  File "d:\code\python\ct83-pc\venv\metaflow\lib\site-packages\metaflow\__init__.py", line 45, in <module>
    from .event_logger import EventLogger
  File "d:\code\python\ct83-pc\venv\metaflow\lib\site-packages\metaflow\event_logger.py", line 1, in <module>
    from .sidecar import SidecarSubProcess
  File "d:\code\python\ct83-pc\venv\metaflow\lib\site-packages\metaflow\sidecar.py", line 4, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

```

### What I think the problem is?
The module fctnl is not available on Windows systems, which makes it impossible to run metaflow on Windows. 

I am open to suggestions. 🤔

Update 1
### Obvious Solution - Windows Sub-System for Linux
This is what I ended up doing, I used Ubuntu with [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

#### References
https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl
https://github.com/cs01/gdbgui/issues/18
https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows

**Comment by seeravikiran** [comment]
Thanks for reporting this. This was also reported to us via the gitter channel and I came to the same finding as you.

The other user was open to running it in a Linux environment. Other options that come to mind are perhaps leveraging docker for windows.

In the immediate horizon, we don’t have an easy resolution for our windows users. But happy to look around if other suggestions to run in a Linux like environment don’t work for you.

**Comment by CT83** [comment]
Nah, using Docker seems like a doable fix for now. I updated the issue to issue include the alternative I used.

**Comment by savingoyal** [comment]
Closing this issue - we don’t have active plans for windows support.
