### ISSUE TITLE
Fix `metaflow pull tutorials` for metaflow conda package

### ISSUE THREAD

**Issue by savingoyal** [Netflix/metaflow#1016]

**Comment by ashrielbrian** [comment]
I'm unable to run `metaflow tutorials pull` either when running from a `conda` environment:

```bash
(metaflow) briant@Ashriels-MacBook-Pro Tapway % metaflow tutorials pull
Metaflow (2.7.17)

Traceback (most recent call last):
  File "/Users/briant/opt/anaconda3/envs/metaflow/bin/metaflow", line 5, in <module>
    from metaflow.cmd.main_cli import start
  File "/Users/briant/opt/anaconda3/envs/metaflow/lib/python3.8/site-packages/metaflow/cmd/main_cli.py", line 124, in <module>
    start()
  File "/Users/briant/opt/anaconda3/envs/metaflow/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/briant/opt/anaconda3/envs/metaflow/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/briant/opt/anaconda3/envs/metaflow/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/briant/opt/anaconda3/envs/metaflow/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/briant/opt/anaconda3/envs/metaflow/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/briant/opt/anaconda3/envs/metaflow/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/briant/opt/anaconda3/envs/metaflow/lib/python3.8/site-packages/metaflow/cmd/tutorials_cmd.py", line 104, in pull
    episodes = get_all_episodes()
  File "/Users/briant/opt/anaconda3/envs/metaflow/lib/python3.8/site-packages/metaflow/cmd/tutorials_cmd.py", line 59, in get_all_episodes
    for name in sorted(os.listdir(get_tutorials_dir())):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/briant/opt/anaconda3/envs/metaflow/lib/python3.8/site-packages/metaflow/metaflow/tutorials'

```

Looks like this is because in `tutorials_cmd.py` line 24,`metaflow` is hardcoded, and the directory follows the repository structure, whereas conda "flattens" the parent `metaflow/` directory.

**Comment by savingoyal** [comment]
Thanks for the PR!
