### ISSUE TITLE
S3 Errors when using s3.get_all() not handled properly and cause crash

### ISSUE THREAD

**Issue by rickyshelton** [Netflix/metaflow#104]
Metaflow v2.0.1
Python 3.7

When trying to load files from S3 using `s3.get_all()` (and potentially `get_recursive()` looking at the code), if you encounter an S3 error (either due to permissions or some other error) it is not handled properly, and the execution crashes without useful output.

When trying to raise a `MetaflowS3Exception` in `_read_many_files` it's trying to reference `prefixes[0]`. 
https://github.com/Netflix/metaflow/blob/master/metaflow/datatools/s3.py#L577

When called called from `get_recursive`, prefixes is a map: `map(self._url, keys)`
https://github.com/Netflix/metaflow/blob/master/metaflow/datatools/s3.py#L418

This causes 
`TypeError: 'map' object is not subscriptable` instead of the original Exception being raised and handled as usual.

This is probably a Python2 vs Python3 issue.

Logs

```
Task is starting (status SUBMITTED)...
Task is starting (status RUNNABLE)...
Task is starting (status STARTING)...
Task is starting (status RUNNING)...
Setting up task environment.
Downloading code package.
Code package downloaded.
Bootstrapping environment.
Environment bootstrapped.
Task is starting.
<flow MetaflowExampleProject step start> failed:
    Internal error
Traceback (most recent call last):
  File "/metaflow/metaflow/cli.py", line 853, in main
    start(auto_envvar_prefix='METAFLOW', obj=state)
  File "/metaflow/metaflow_MetaflowExampleProject_linux-64_cffadb7002d862de02233a30fad8e993ff54043e/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(args, kwargs)
  File "/metaflow/metaflow_MetaflowExampleProject_linux-64_cffadb7002d862de02233a30fad8e993ff54043e/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/metaflow/metaflow_MetaflowExampleProject_linux-64_cffadb7002d862de02233a30fad8e993ff54043e/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/metaflow/metaflow_MetaflowExampleProject_linux-64_cffadb7002d862de02233a30fad8e993ff54043e/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/metaflow/metaflow_MetaflowExampleProject_linux-64_cffadb7002d862de02233a30fad8e993ff54043e/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(args, kwargs)
  File "/metaflow/metaflow_MetaflowExampleProject_linux-64_cffadb7002d862de02233a30fad8e993ff54043e/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, args, kwargs)
  File "/metaflow/metaflow/cli.py", line 430, in step
    max_user_code_retries)
  File "/metaflow/metaflow/task.py", line 390, in run_step
    self._exec_step_function(step_func)
  File "/metaflow/metaflow/task.py", line 47, in _exec_step_function
    step_function()
  File "metaflow-example.py", line 19, in start
    res = s3.get_all()
  File "/metaflow/metaflow/datatools/s3.py", line 440, in get_all
    return self.get_recursive([None])
  File "/metaflow/metaflow/datatools/s3.py", line 426, in get_recursive
    return list(starmap(S3Object, _get()))
  File "/metaflow/metaflow/datatools/s3.py", line 424, in _get
    for s3prefix, s3url, fname in res:
  File "/metaflow/metaflow/datatools/s3.py", line 577, in _read_many_files
    "Error: %s" % (prefixes[0], stderr))
TypeError: 'map' object is not subscriptable
Batch error:
Task crashed. This could be a transient error. Use @retry to retry.
Task failed.
Workflow failed.
```

**Comment by savingoyal** [comment]
Thanks for the bug report. We will take a look and fix.

**Comment by seeravikiran** [comment]
@romain-intel I remember us seeing a similar issue like this before (with the client). Do you remember, or want to take a look at this?
