### ISSUE TITLE
A KeyError will happen when I use '-' in the parameter

### ISSUE THREAD

**Issue by bryanyang0528** [Netflix/metaflow#111]
This is my parameter
```python
colsample_bytree = Parameter('colsample-bytree', default=1.0)
```
When I execute mlflow run, it will show below.

```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/metaflow/cli.py", line 853, in main
    start(auto_envvar_prefix='METAFLOW', obj=state)
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(args, kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(args, kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/metaflow/cli.py", line 508, in wrapper
    return func(args, kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, args, kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/metaflow/cli.py", line 607, in run
    parameters.set_parameters(obj.flow, kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/metaflow/parameters.py", line 238, in set_parameters
    val = kwargs[param.name.lower()]
KeyError: 'colsample-bytree'
```

**Comment by romain-intel** [comment]
Why not just do `colsample_bytree = Parameter('colsample_bytree', defaults=1.0)`. The syntax of Parameter follows that of a namedtuple. We could, however, do like namedtuple exactly and return a ValueError if the name is invalid. I would prefer a fix like that than one that changes characters.

**Comment by bryanyang0528** [comment]
In this file (`https://github.com/Netflix/metaflow/blob/master/metaflow/cli.py`), Metaflow used `Click` to parse command arguments. `Click` will convert hyphen in the argument to underscore automatically. So I just would like to keep consistency between cli argument naming rules.

**Comment by romain-intel** [comment]
That makes sense. It seems this was a Click behavior change a while ago (about a year or so). Checking something with the team and I'll resolve this shortly. Thanks for the PR.

**Comment by savingoyal** [comment]
#113 fixes this.
