### ISSUE TITLE
OSError: could not get source code

### ISSUE THREAD

**Issue by pdMa2s** [Netflix/metaflow#133]
Traceback (most recent call last):
  File "/home/pdma2s/Documents/scubic/workers/forecast/models/MachineLearningScubicModels.py", line 195, in <module>
    TrainingFlow(NeuralNetworkScubicModel("test", "PE_Lemede"), "PE_Lemede")
  File "/home/pdma2s/Documents/scubic/workers/forecast/models/flows/TrainingFlowSteps.py", line 73, in __init__
    super().__init__()
  File "/home/pdma2s/.local/lib/python3.8/site-packages/metaflow/flowspec.py", line 70, in __init__
    self._graph = FlowGraph(self.__class__)
  File "/home/pdma2s/.local/lib/python3.8/site-packages/metaflow/graph.py", line 132, in __init__
    self.nodes = self._create_nodes(flow)
  File "/home/pdma2s/.local/lib/python3.8/site-packages/metaflow/graph.py", line 139, in _create_nodes
    tree = ast.parse(inspect.getsource(module)).body
  File "/usr/lib/python3.8/inspect.py", line 985, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/lib/python3.8/inspect.py", line 967, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python3.8/inspect.py", line 798, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

I get this error when I try to initialize a flow

**Comment by savingoyal** [comment]
How are you executing your flow? What does your flow look like?

**Comment by pdMa2s** [comment]
@savingoyal thank you for your reply. I managed to solve the problem. I was initializing the flow class in another file via import and apparently it causes this error, I didn't know that, nor do I think its stated in the documentation.

**Comment by pdMa2s** [comment]
Hi @Alnamkani, it was quite some time ago but I think that solved it.
