### ISSUE TITLE
(TooManyRequestsException) when calling the DescribeJobs operation

### ISSUE THREAD

**Issue by andaag** [Netflix/metaflow#138]
When testing metaflow with a spot compute environment + 32 max workers I hit this issue:

```
2020-02-22 19:40:13.732 [33/fetchdata/237 (pid 28298)] Internal error
2020-02-22 19:40:13.734 [33/fetchdata/237 (pid 28298)] Traceback (most recent call last):
2020-02-22 19:40:13.734 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/metaflow/cli.py", line 853, in main
2020-02-22 19:40:13.734 [33/fetchdata/237 (pid 28298)] start(auto_envvar_prefix='METAFLOW', obj=state)
2020-02-22 19:40:13.734 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/click/core.py", line 764, in __call__
2020-02-22 19:40:13.735 [33/fetchdata/237 (pid 28298)] return self.main(args, kwargs)
2020-02-22 19:40:13.735 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/click/core.py", line 717, in main
2020-02-22 19:40:13.735 [33/fetchdata/237 (pid 28298)] rv = self.invoke(ctx)
2020-02-22 19:40:13.735 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
2020-02-22 19:40:13.736 [33/fetchdata/237 (pid 28298)] return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-02-22 19:40:13.736 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
2020-02-22 19:40:13.736 [33/fetchdata/237 (pid 28298)] return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-02-22 19:40:13.736 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/click/core.py", line 956, in invoke
2020-02-22 19:40:13.736 [33/fetchdata/237 (pid 28298)] return ctx.invoke(self.callback, ctx.params)
2020-02-22 19:40:13.765 [33/fetchdata/232 (pid 28173)] [30e98b14-0e4c-42a3-a460-3b0cec12b171] Task is starting (status RUNNABLE)...
2020-02-22 19:40:13.765 [33/fetchdata/232 (pid 28173)] Internal error
2020-02-22 19:40:13.767 [33/fetchdata/232 (pid 28173)] Traceback (most recent call last):
2020-02-22 19:40:13.768 [33/fetchdata/232 (pid 28173)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/metaflow/cli.py", line 853, in main
2020-02-22 19:40:13.768 [33/fetchdata/232 (pid 28173)] start(auto_envvar_prefix='METAFLOW', obj=state)
2020-02-22 19:40:13.768 [33/fetchdata/232 (pid 28173)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/click/core.py", line 764, in __call__
2020-02-22 19:40:13.768 [33/fetchdata/232 (pid 28173)] return self.main(args, kwargs)
2020-02-22 19:40:13.769 [33/fetchdata/232 (pid 28173)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/click/core.py", line 717, in main
2020-02-22 19:40:13.769 [33/fetchdata/232 (pid 28173)] rv = self.invoke(ctx)
2020-02-22 19:40:13.769 [33/fetchdata/232 (pid 28173)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
2020-02-22 19:40:13.769 [33/fetchdata/232 (pid 28173)] return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-02-22 19:40:13.770 [33/fetchdata/232 (pid 28173)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
2020-02-22 19:40:13.770 [33/fetchdata/232 (pid 28173)] return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-02-22 19:40:13.770 [33/fetchdata/232 (pid 28173)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/click/core.py", line 956, in invoke
2020-02-22 19:40:13.770 [33/fetchdata/232 (pid 28173)] return ctx.invoke(self.callback, ctx.params)
2020-02-22 19:40:14.079 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/click/core.py", line 555, in invoke
2020-02-22 19:40:14.079 [33/fetchdata/237 (pid 28298)] return callback(args, kwargs)
2020-02-22 19:40:14.080 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
2020-02-22 19:40:14.080 [33/fetchdata/237 (pid 28298)] return f(get_current_context(), args, kwargs)
2020-02-22 19:40:14.080 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/metaflow/plugins/aws/batch/batch_cli.py", line 265, in step
2020-02-22 19:40:14.080 [33/fetchdata/237 (pid 28298)] batch.wait(echo=echo)
2020-02-22 19:40:14.080 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/metaflow/plugins/aws/batch/batch.py", line 188, in wait
2020-02-22 19:40:14.081 [33/fetchdata/237 (pid 28298)] wait_for_launch(self.job)
2020-02-22 19:40:14.081 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/metaflow/plugins/aws/batch/batch.py", line 169, in wait_for_launch
2020-02-22 19:40:14.081 [33/fetchdata/237 (pid 28298)] if status != job.status or (time.time()-t) > 30:
2020-02-22 19:40:14.081 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/metaflow/plugins/aws/batch/batch_client.py", line 219, in status
2020-02-22 19:40:14.081 [33/fetchdata/237 (pid 28298)] if not self.is_done:
2020-02-22 19:40:14.081 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/metaflow/plugins/aws/batch/batch_client.py", line 238, in is_done
2020-02-22 19:40:14.081 [33/fetchdata/237 (pid 28298)] self.update()
2020-02-22 19:40:14.082 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/metaflow/plugins/aws/batch/batch_client.py", line 196, in update
2020-02-22 19:40:14.082 [33/fetchdata/237 (pid 28298)] self._update()
2020-02-22 19:40:14.082 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/metaflow/plugins/aws/batch/batch_client.py", line 167, in wrapped
2020-02-22 19:40:14.082 [33/fetchdata/237 (pid 28298)] func(args, kwargs)
2020-02-22 19:40:14.082 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/metaflow/plugins/aws/batch/batch_client.py", line 190, in _update
2020-02-22 19:40:14.082 [33/fetchdata/237 (pid 28298)] data = self._client.describe_jobs(jobs=[self._id])
2020-02-22 19:40:14.082 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
2020-02-22 19:40:14.083 [33/fetchdata/237 (pid 28298)] return self._make_api_call(operation_name, kwargs)
2020-02-22 19:40:14.083 [33/fetchdata/237 (pid 28298)] File "/home/neuron/src/sch/p10n-experiments-m2/.venv/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
2020-02-22 19:40:14.083 [33/fetchdata/237 (pid 28298)] raise error_class(parsed_response, operation_name)
2020-02-22 19:40:14.083 [33/fetchdata/237 (pid 28298)] botocore.exceptions.ClientError: An error occurred (TooManyRequestsException) when calling the DescribeJobs operation (reached max retries: 4): Too Many Requests
```

It'd be good with some exponential backoff and retrying here 👍.

**Comment by savingoyal** [comment]
Opened #160 to fix this.

**Comment by savingoyal** [comment]
Closing since #160 fixes this.
