### ISSUE TITLE
ValueError: Cannot locate step_decorator plugin 'batch' at 'metaflow.plugins.aws.batch.batch_decorator'

### ISSUE THREAD

**Issue by linkedlist771** [Netflix/metaflow#1635]
Hi, guys. I am running your tutorial on windows. And I find that the first example can not be executed on my computer:

```bash
C:/Users/23174/anaconda3/envs/metaflow/python.exe "c:/Users/23174/Desktop/GitHub Project/metaflow/metaflow/tutorials/00-helloworld/helloworld.py"
Traceback (most recent call last):
  File "C:\Users\23174\anaconda3\envs\metaflow\Lib\site-packages\metaflow\extension_support\plugins.py", line 137, in resolve_plugins
    plugin_module = importlib.import_module(path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23174\anaconda3\envs\metaflow\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\23174\anaconda3\envs\metaflow\Lib\site-packages\metaflow\plugins\kubernetes\kubernetes_decorator.py", line 26, in <module>
    from metaflow.sidecar import Sidecar
  File "C:\Users\23174\anaconda3\envs\metaflow\Lib\site-packages\metaflow\sidecar\__init__.py", line 1, in <module>
    from .sidecar import Sidecar
  File "C:\Users\23174\anaconda3\envs\metaflow\Lib\site-packages\metaflow\sidecar\sidecar.py", line 1, in <module>
    from .sidecar_subprocess import SidecarSubProcess
  File "C:\Users\23174\anaconda3\envs\metaflow\Lib\site-packages\metaflow\sidecar\sidecar_subprocess.py", line 4, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\23174\Desktop\GitHub Project\metaflow\metaflow\tutorials\00-helloworld\helloworld.py", line 1, in <module>
    from metaflow import FlowSpec, step
  File "C:\Users\23174\anaconda3\envs\metaflow\Lib\site-packages\metaflow\__init__.py", line 115, in <module>
    from .plugins.datatools import S3
  File "C:\Users\23174\anaconda3\envs\metaflow\Lib\site-packages\metaflow\plugins\__init__.py", line 132, in <module>
    STEP_DECORATORS = resolve_plugins("step_decorator")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23174\anaconda3\envs\metaflow\Lib\site-packages\metaflow\extension_support\plugins.py", line 139, in resolve_plugins 
    raise ValueError(
ValueError: Cannot locate step_decorator plugin 'kubernetes' at 'metaflow.plugins.kubernetes.kubernetes_decorator'`
```

But it is fine on a ubuntu server.

**Comment by romain-intel** [comment]
Metaflow is currently only supported on Linux or MacOS, not on Windows.
