### ISSUE TITLE
Permission error when running tutorial episode 04

### ISSUE THREAD

**Issue by xujiboy** [Netflix/metaflow#179]
Hi, I am new to `metaflow` and currently trying to run through the tutorials in my work environment. As a non-root user of `conda`, I don't have write permission for where `conda` is installed: `/opt/miniconda`, so I ran into this error when executing episode 04 in which `@conda` was used:
```
PermissionError: [Errno 13] Permission denied: '/opt/miniconda/mf_env-creation.lock'
```
Is there some configuration I can do to assign a new location where this `mf_env-creation.lock` will be written?

`conda` version = 4.8.3
`metaflow` version = 2.0.1

**Comment by savingoyal** [comment]
Thanks for opening the issue. We will make it configurable in the next release.

**Comment by oonisim** [comment]
@xujiboy , I had the same issue and workaround was installing user level anaconda. When installing anaconda, you can choose "for all users" which will install /opt where you need sudo etc to write there, or choose "user only" installation with which you can install conda in your home directory which you will not get the error.

**Comment by xujiboy** [comment]
Hi @oonisim Thank you very much for the tip. My workspace situation is kinda constrained: `conda` was installed by admin in jupyterhub "for all users" and as users we are stuck with it. Although we can create virtual env with it we don't have write permission at `/opt/...`. Installing `miniconda` myself at my own user directory will probably mess up with the admin-installed one, so right now I am hesitant to go this route.

**Comment by romain-intel** [comment]
@xujiboy, could you let me know what it says when you run `conda info` in the `envs directories` section. Particularly interested to check if the directory listed there is writeable by you (I suspect it will be and may be something like `~/.conda/envs`. If that is the case, I will make a patch to change the location of the lock file to that location. Making it configurable may have the undesired side-effect of not being a global enough lock but putting in where your environments are created may do the trick.

**Comment by xujiboy** [comment]
Hi @romain-intel Thank you very much for looking into this. Shown below is the output of `conda info`: (I hide the `channel URLs` as "..." since they are related to my workplace artifactory repos)

```bash
   active environment : base
    active env location : /opt/miniconda
            shell level : 1
       user config file : /home/ji.xu/.condarc
 populated config files : /etc/conda/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.5.final.0
       virtual packages : __glibc=2.17
       base environment : /opt/miniconda  (read only)
           channel URLs : ...
          package cache : /opt/miniconda/pkgs
                          /home/ji.xu/.conda/pkgs
       envs directories : /home/ji.xu/.conda/envs
                          /opt/miniconda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.5 Linux/3.10.0-957.21.2.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 1931:1001
             netrc file : None
           offline mode : False
```
So the admin-created `base` env is located at `/opt/miniconda/envs`, while any env that I created as a user are located at `/home/ji.xu/.conda/envs`, as you predicted. Do you think a patch can be made to place lock file there as you suggested? Many thanks~

**Comment by sodre** [comment]
I wanted to add that I am also experiencing the same error. We have conda installed using [RPMs/DEBs](https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html).

For completeness, here is my full stack-trace:
```python-traceback
$ python 04-playlist-plus/playlist.py --environment=conda run
Metaflow 2.2.0 executing PlayListFlow for user:pcarlos
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
2020-08-13 15:46:18.186 Bootstrapping conda environment...(this could take a few minutes)
    Internal error
Traceback (most recent call last):
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/metaflow/cli.py", line 884, in main
    start(auto_envvar_prefix='METAFLOW', obj=state)
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(args, kwargs)
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(args, kwargs)
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/metaflow/cli.py", line 524, in wrapper
    return func(args, kwargs)
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, args, kwargs)
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/metaflow/cli.py", line 605, in run
    before_run(obj, tags, decospecs + obj.environment.decospecs())
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/metaflow/cli.py", line 661, in before_run
    obj.package = MetaflowPackage(obj.flow, obj.environment, obj.logger, obj.package_suffixes)
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/metaflow/package.py", line 32, in __init__
    deco.package_init(flow,
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/metaflow/plugins/conda/conda_step_decorator.py", line 215, in package_init
    self._prepare_step_environment(step, self.local_root)
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/metaflow/plugins/conda/conda_step_decorator.py", line 165, in _prepare_step_environment
    env_id = self._resolve_step_environment(ds_root)
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/metaflow/plugins/conda/conda_step_decorator.py", line 115, in _resolve_step_environment
    self.conda.create(self.step, env_id, deps, architecture=self.architecture)
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/metaflow/plugins/conda/conda.py", line 47, in create
    with CondaLock(self._env_lock_file(env_id)):
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/metaflow/plugins/conda/conda.py", line 213, in __enter__
    self._acquire()
  File "/home/pcarlos/.conda/envs/metaflow/lib/python3.8/site-packages/metaflow/plugins/conda/conda.py", line 190, in _acquire
    self.fd = os.open(self.lock, os.O_CREAT |
PermissionError: [Errno 13] Permission denied: '/opt/conda/mf_env-creation.lock'
```

**Comment by sodre** [comment]
@savingoyal It is possible that metaflow's logic for acquiring locks for conda is redundant with conda's own [locking](https://github.com/conda/conda/blob/master/conda/lock.py) mechanism.

**Comment by romain-intel** [comment]
Apologies for the delay in response. Yes, I think we can make a patch for this. I will discuss with @savingoyal this week but we should be able to use the "envs directories" information to pick where to put the lock file. I do want to discuss with @savingoyal first to see if we still need the lock (maybe we can skip it as @sodre mentions).

**Comment by sodre** [comment]
> Apologies for the delay in response. Yes, I think we can make a patch for this. I will discuss with @savingoyal this week but we should be able to use the "envs directories" information to pick where to put the lock file. I do want to discuss with @savingoyal first to see if we still need the lock (maybe we can skip it as @sodre mentions).

No issues, I issued a PR with the environments directory approach. Happy to help further if needed.

**Comment by romain-intel** [comment]
Thanks a lot. We will get this merged and you unblocked!
