### ISSUE TITLE
attributes defined in early step lost in a foreach flow

### ISSUE THREAD

**Issue by xujiboy** [Netflix/metaflow#205]
Hi,
I have a flow (link to the [gist](https://gist.github.com/xujiboy/08224c8a6e5803a5c8faf8888471cc75)) that looks like the following:
<details>
  <summary>Click to expand</summary>
 
```python
from metaflow import FlowSpec, step, Parameter


def script_path(filename):
    """
    A convenience function to get the absolute path to a file in this
    tutorial's directory. This allows the tutorial to be launched from any
    directory.

    """
    import os

    filepath = os.path.join(os.path.dirname(__file__))
    return os.path.join(filepath, filename)
    
class TestForeachFlow(FlowSpec):
    """
    A flow to test foreach flow.

    The flow performs the following steps:
    1) Setup parameters.
    2) Fork to foreach step.
    3) Alter the value of input c.
    4) Joins all the altered c as a list.
    5) End.

    """
    # initial attributes
    init_a = Parameter('init_a',
                         help = 'the initial attribute a',
                         default = 100)
        
    @step
    def start(self):
        """
        Setup parameters.

        """

        self.param = dict(foo = 2)
        
        self.next(self.fork)

    @step
    def fork(self):
        """
        Fork to foreach step.

        """
            
        self.c_list = [1,2,3,4]
        
        self.next(self.alter_c, foreach='c_list')

    @step
    def alter_c(self):
        """
        This step alters the value of input c.

        """
        
        self.c = self.input
        self.altered_c = self.c + 1000
        
        self.next(self.join)
        
    @step
    def join(self, inputs):
        """
        This step joins all the altered c as a list
        """
        self.altered_c_list = [input.altered_c for input in inputs]
        self.foo = self.param.get('foo')
        self.result = [i+ self.foo for i in self.altered_c_list]
        
        self.next(self.end)
        
    @step
    def end(self):
        """
        end.

        """
        pass


if __name__ == '__main__':
    TestForeachFlow()

```
</details>

But when I ran it it failed at the `join` step because the attribute `self.param` is lost. The full trace is show below:

<details>
  <summary>Click to expand</summary>

```bash
Metaflow 2.0.1 executing TestForeachFlow for user:ji.xu
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint not found, so extra checks are disabled.
2020-05-22 11:05:25.324 Workflow starting (run-id 1590170725321423):
2020-05-22 11:05:25.327 [1590170725321423/start/1 (pid 54171)] Task is starting.
2020-05-22 11:05:25.690 [1590170725321423/start/1 (pid 54171)] Task finished successfully.
2020-05-22 11:05:25.715 [1590170725321423/fork/2 (pid 54255)] Task is starting.
2020-05-22 11:05:26.050 [1590170725321423/fork/2 (pid 54255)] Foreach yields 4 child steps.
2020-05-22 11:05:26.050 [1590170725321423/fork/2 (pid 54255)] Task finished successfully.
2020-05-22 11:05:26.057 [1590170725321423/alter_c/3 (pid 54296)] Task is starting.
2020-05-22 11:05:26.080 [1590170725321423/alter_c/4 (pid 54297)] Task is starting.
2020-05-22 11:05:26.086 [1590170725321423/alter_c/5 (pid 54299)] Task is starting.
2020-05-22 11:05:26.092 [1590170725321423/alter_c/6 (pid 54304)] Task is starting.
2020-05-22 11:05:26.417 [1590170725321423/alter_c/3 (pid 54296)] Task finished successfully.
2020-05-22 11:05:26.424 [1590170725321423/alter_c/5 (pid 54299)] Task finished successfully.
2020-05-22 11:05:26.431 [1590170725321423/alter_c/4 (pid 54297)] Task finished successfully.
2020-05-22 11:05:26.438 [1590170725321423/alter_c/6 (pid 54304)] Task finished successfully.
2020-05-22 11:05:26.443 [1590170725321423/join/7 (pid 54357)] Task is starting.
2020-05-22 11:05:26.751 [1590170725321423/join/7 (pid 54357)] <flow TestForeachFlow step join> failed:
2020-05-22 11:05:26.753 [1590170725321423/join/7 (pid 54357)] Internal error
2020-05-22 11:05:26.753 [1590170725321423/join/7 (pid 54357)] Traceback (most recent call last):
2020-05-22 11:05:26.753 [1590170725321423/join/7 (pid 54357)] File "/opt/miniconda/lib/python3.7/site-packages/metaflow/cli.py", line 853, in main
2020-05-22 11:05:26.753 [1590170725321423/join/7 (pid 54357)] start(auto_envvar_prefix='METAFLOW', obj=state)
2020-05-22 11:05:26.753 [1590170725321423/join/7 (pid 54357)] File "/opt/miniconda/lib/python3.7/site-packages/click/core.py", line 764, in __call__
2020-05-22 11:05:26.753 [1590170725321423/join/7 (pid 54357)] return self.main(args, kwargs)
2020-05-22 11:05:26.753 [1590170725321423/join/7 (pid 54357)] File "/opt/miniconda/lib/python3.7/site-packages/click/core.py", line 717, in main
2020-05-22 11:05:26.754 [1590170725321423/join/7 (pid 54357)] rv = self.invoke(ctx)
2020-05-22 11:05:26.754 [1590170725321423/join/7 (pid 54357)] File "/opt/miniconda/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
2020-05-22 11:05:26.754 [1590170725321423/join/7 (pid 54357)] return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-05-22 11:05:26.754 [1590170725321423/join/7 (pid 54357)] File "/opt/miniconda/lib/python3.7/site-packages/click/core.py", line 956, in invoke
2020-05-22 11:05:26.754 [1590170725321423/join/7 (pid 54357)] return ctx.invoke(self.callback, ctx.params)
2020-05-22 11:05:26.754 [1590170725321423/join/7 (pid 54357)] File "/opt/miniconda/lib/python3.7/site-packages/click/core.py", line 555, in invoke
2020-05-22 11:05:26.754 [1590170725321423/join/7 (pid 54357)] return callback(args, kwargs)
2020-05-22 11:05:26.754 [1590170725321423/join/7 (pid 54357)] File "/opt/miniconda/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
2020-05-22 11:05:26.754 [1590170725321423/join/7 (pid 54357)] return f(get_current_context().obj, args, kwargs)
2020-05-22 11:05:26.801 [1590170725321423/join/7 (pid 54357)] File "/opt/miniconda/lib/python3.7/site-packages/metaflow/cli.py", line 430, in step
2020-05-22 11:05:26.801 [1590170725321423/join/7 (pid 54357)] max_user_code_retries)
2020-05-22 11:05:26.801 [1590170725321423/join/7 (pid 54357)] File "/opt/miniconda/lib/python3.7/site-packages/metaflow/task.py", line 373, in run_step
2020-05-22 11:05:26.801 [1590170725321423/join/7 (pid 54357)] self._exec_step_function(step_func, input_obj)
2020-05-22 11:05:26.801 [1590170725321423/join/7 (pid 54357)] File "/opt/miniconda/lib/python3.7/site-packages/metaflow/task.py", line 49, in _exec_step_function
2020-05-22 11:05:26.801 [1590170725321423/join/7 (pid 54357)] step_function(input_obj)
2020-05-22 11:05:26.801 [1590170725321423/join/7 (pid 54357)] File "99-flow-testing/test-foreach-flow.py", line 73, in join
2020-05-22 11:05:26.802 [1590170725321423/join/7 (pid 54357)] self.foo = self.param.get('foo')
2020-05-22 11:05:26.802 [1590170725321423/join/7 (pid 54357)] File "/opt/miniconda/lib/python3.7/site-packages/metaflow/flowspec.py", line 128, in __getattr__
2020-05-22 11:05:26.802 [1590170725321423/join/7 (pid 54357)] (self.name, name))
2020-05-22 11:05:26.802 [1590170725321423/join/7 (pid 54357)] AttributeError: Flow TestForeachFlow has no attribute 'param'
2020-05-22 11:05:26.802 [1590170725321423/join/7 (pid 54357)] 
2020-05-22 11:05:26.804 [1590170725321423/join/7 (pid 54357)] Task failed.
2020-05-22 11:05:26.805 Workflow failed.
2020-05-22 11:05:26.805 Terminating 0 active tasks...
2020-05-22 11:05:26.805 Flushing logs...
    Step failure:
    Step join (task-id 7) failed.
```
</details>

May I know if this behaviour is expected or is it a bug? I can confirm that if I don't have the `foreach` step and have a linear flow instead, the flow can be ran successfully. I am using `metaflow 2.0.1` in `Python 3.7.5`

**Comment by savingoyal** [comment]
@xujiboy This is the expected behavior because you will now have multiple copies of the same param. You can use `merge_artifacts` as documented in this section - [data flow through the graph](https://docs.metaflow.org/metaflow/basics#data-flow-through-the-graph).

**Comment by xujiboy** [comment]
Thank you very much @savingoyal .

**Comment by dksahuji** [comment]
Can someone talk about the design decision here? I mean unambiguous variables can be persisted.
