### ISSUE TITLE
Windows Issue with Tutorial: No module named 'fcntl'

### ISSUE THREAD

**Issue by nickfranciose** [Netflix/metaflow#23]
Hello metaflow, 

I am interested in learning about the metaflow offering but am hitting a snag in the very first tutorial: 

λ python 00-helloworld/helloworld.py show
Traceback (most recent call last):
  File "00-helloworld/helloworld.py", line 1, in <module>
    from metaflow import FlowSpec, step
  File "C:\Users\Nick.Franciose\AppData\Local\Programs\Python\Python36\lib\site-packages\metaflow\__init__.py", line 45, in <module>
    from .event_logger import EventLogger
  File "C:\Users\Nick.Franciose\AppData\Local\Programs\Python\Python36\lib\site-packages\metaflow\event_logger.py", line 1, in <module>
    from .sidecar import SidecarSubProcess
  File "C:\Users\Nick.Franciose\AppData\Local\Programs\Python\Python36\lib\site-packages\metaflow\sidecar.py", line 4, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

Stackoverflow suggests fcntl is a linux specific.  Is this offering windows compatible?  If so, do you have a workaround? 

Best,
NIck

**Comment by seeravikiran** [comment]
See:
https://github.com/Netflix/metaflow/issues/10

**Comment by seeravikiran** [comment]
Let me know if I can close this issue once the workaround in #10 works for you.

**Comment by nickfranciose** [comment]
Yes, using WSL solves the issue.  Thanks.
