### ISSUE TITLE
Tutorial episode 6 does not work in AWS

### ISSUE THREAD

**Issue by oonisim** [Netflix/metaflow#241]
# Problem
Tutorial Episode06 (https://docs.metaflow.org/getting-started/tutorials/season-2-scaling-out-and-up/episode06) in AWS does not work. Episode 05 worked in AWS.

```
python 02-statistics/stats.py --with batch run --max-workers 4
Metaflow 2.0.5 executing MovieStatsFlow for user:****
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
2020-07-01 20:33:52.913 Including file 02-statistics/movies.csv of size 191KB 
2020-07-01 20:33:53.334 Workflow starting (run-id 2):
2020-07-01 20:33:53.830 [2/start/6 (pid 97065)] Task is starting.
2020-07-01 20:33:54.681 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c] Task is starting (status SUBMITTED)...
2020-07-01 20:34:00.120 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c] Task is starting (status RUNNABLE)...
2020-07-01 20:34:04.506 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c] Task is starting (status STARTING)...
2020-07-01 20:34:09.803 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c] Task is starting (status RUNNING)...
2020-07-01 20:34:16.447 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c] Setting up task environment.
2020-07-01 20:34:26.411 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c] Downloading code package.
2020-07-01 20:34:26.411 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c] Code package downloaded.
2020-07-01 20:34:26.411 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c] Task is starting.
2020-07-01 20:34:26.411 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c] <flow MovieStatsFlow step start> failed:
2020-07-01 20:34:26.411 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]     Internal error
2020-07-01 20:34:26.411 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c] Traceback (most recent call last):
2020-07-01 20:34:26.411 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]   File "/metaflow/metaflow/cli.py", line 857, in main
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]     start(auto_envvar_prefix='METAFLOW', obj=state)
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]   File "/root/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]     return self.main(args, kwargs)
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]   File "/root/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]     rv = self.invoke(ctx)
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]   File "/root/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]     return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]   File "/root/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]     return ctx.invoke(self.callback, ctx.params)
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]   File "/root/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]     return callback(args, kwargs)
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]   File "/root/.local/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
2020-07-01 20:34:26.412 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]     return f(get_current_context().obj, args, kwargs)
2020-07-01 20:34:29.661 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]   File "/metaflow/metaflow/cli.py", line 432, in step
2020-07-01 20:34:29.661 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]     max_user_code_retries)
2020-07-01 20:34:29.661 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]   File "/metaflow/metaflow/task.py", line 393, in run_step
2020-07-01 20:34:29.662 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]     self._exec_step_function(step_func)
2020-07-01 20:34:29.662 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]   File "/metaflow/metaflow/task.py", line 47, in _exec_step_function
2020-07-01 20:34:29.662 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]     step_function()
2020-07-01 20:34:29.662 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]   File "stats.py", line 41, in start
2020-07-01 20:34:29.662 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c]     import pandas
2020-07-01 20:34:29.662 [2/start/6 (pid 97065)] [6ab5d921-7ded-4b9b-8e80-2ee486d16d1c] ModuleNotFoundError: No module named 'pandas'
2020-07-01 20:34:29.662 [2/start/6 (pid 97065)] Batch error:
2020-07-01 20:34:29.761 [2/start/6 (pid 97065)] Essential container in task exited This could be a transient error. Use @retry to retry.
2020-07-01 20:34:29.761 [2/start/6 (pid 97065)] 
2020-07-01 20:34:30.305 [2/start/6 (pid 97065)] Task failed.
2020-07-01 20:34:30.305 Workflow failed.
2020-07-01 20:34:30.305 Terminating 0 active tasks...
2020-07-01 20:34:30.305 Flushing logs...
    Step failure:
    Step start (task-id 6) failed.
```

As per https://github.com/Netflix/metaflow/issues/95, updated the code as below.
```
$ diff 02-statistics/stats.old.py 02-statistics/stats.py 
1c1
< from metaflow import FlowSpec, step, IncludeFile
---
> from metaflow import FlowSpec, step, IncludeFile, Parameter, conda, conda_base
16a17,31
> def get_python_version():
>     """
>     A convenience function to get the python version used to run this
>     tutorial. This ensures that the conda environment is created with an
>     available version of python.
> 
>     """
>     import platform
>     versions = {'2' : '2.7.15',
>                 '3' : '3.7.3'}
>     return versions[platform.python_version_tuple()[0]]
> 
> 
> # Use the specified version of python for this flow.
> @conda_base(python=get_python_version())
31a47
>     @conda(libraries={'pandas': '0.24.2'})
58a75
>     @conda(libraries={'pandas': '0.24.2'})
83a101
>     @conda(libraries={'pandas': '0.24.2'})
```

However another error.
```
$ python 02-statistics/stats.py --with batch --environment=conda  run --max-workers 4
Metaflow 2.0.5 executing MovieStatsFlow for user:****
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
2020-07-01 20:58:41.260 Bootstrapping conda environment...(this could take a few minutes)
    Incompatible environment:
    No conda installation found. Install conda first.
```

So run below but still another error.
```
$ $ pip install conda
Collecting conda
  Using cached conda-4.3.16.tar.gz (299 kB)
Requirement already satisfied: pycosat>=0.6.1 in /Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages (from conda) (0.6.3)
Requirement already satisfied: requests>=2.12.4 in /Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages (from conda) (2.24.0)
Requirement already satisfied: ruamel.yaml>=0.11.14 in /Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages (from conda) (0.16.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages (from requests>=2.12.4->conda) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in /Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages (from requests>=2.12.4->conda) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages (from requests>=2.12.4->conda) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages (from requests>=2.12.4->conda) (2020.6.20)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages (from ruamel.yaml>=0.11.14->conda) (0.2.0)
Using legacy setup.py install for conda, since package 'wheel' is not installed.
Installing collected packages: conda
    Running setup.py install for conda ... done
Successfully installed conda-4.3.16


$ python 02-statistics/stats.py --with batch --environment=conda  run --max-workers 4
Metaflow 2.0.5 executing MovieStatsFlow for user:****
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
2020-07-01 20:59:52.095 Bootstrapping conda environment...(this could take a few minutes)
    Internal error
Traceback (most recent call last):
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/metaflow/plugins/conda/conda.py", line 156, in _call_conda
    'CONDA_USE_ONLY_TAR_BZ2': 'True'
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    kwargs).stdout
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/****/home/repositories/git/user/metaflow/bin/conda', 'info']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/metaflow/cli.py", line 857, in main
    start(auto_envvar_prefix='METAFLOW', obj=state)
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(args, kwargs)
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(args, kwargs)
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/metaflow/cli.py", line 510, in wrapper
    return func(args, kwargs)
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, args, kwargs)
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/metaflow/cli.py", line 591, in run
    before_run(obj, tags, decospecs + obj.environment.decospecs())
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/metaflow/cli.py", line 647, in before_run
    obj.package = MetaflowPackage(obj.flow, obj.environment, obj.logger, obj.package_suffixes)
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/metaflow/package.py", line 33, in __init__
    environment)
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/metaflow/plugins/conda/conda_step_decorator.py", line 215, in package_init
    self._prepare_step_environment(step, self.local_root)
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/metaflow/plugins/conda/conda_step_decorator.py", line 165, in _prepare_step_environment
    env_id = self._resolve_step_environment(ds_root)
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/metaflow/plugins/conda/conda_step_decorator.py", line 109, in _resolve_step_environment
    CondaStepDecorator.conda = Conda()
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/metaflow/plugins/conda/conda.py", line 34, in __init__
    if LooseVersion(self._info()['conda_version']) < LooseVersion('4.6.0'):
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/metaflow/plugins/conda/conda.py", line 92, in _info
    return json.loads(self._call_conda(['info']))
  File "/Users/****/home/repositories/git/user/metaflow/lib/python3.7/site-packages/metaflow/plugins/conda/conda.py", line 170, in _call_conda
    .format(cmd=e.cmd, code=e.returncode, output=e.output))
RuntimeError: command '['/Users/****/home/repositories/git/user/metaflow/bin/conda', 'info']' returned error (1): b''
```

## Environment
Using Python virtualenv. As stated in https://www.anaconda.com/blog/using-pip-in-a-conda-environment, conda environment should only use conda for package management, not mixed with pip. 

```
$ metaflow
Metaflow (2.0.5): More data science, less engineering

http://docs.metaflow.org - Read the documentation
http://chat.metaflow.org - Chat with us
help@metaflow.org        - Get help by email
```

## Episode 5
```
$ python 05-helloaws/helloaws.py run
Metaflow 2.0.5 executing HelloAWSFlow for user:****
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
2020-07-01 20:19:33.141 Workflow starting (run-id 1):
2020-07-01 20:19:33.382 [1/start/2 (pid 96712)] Task is starting.
2020-07-01 20:19:35.117 [1/start/2 (pid 96712)] HelloAWS is starting.
2020-07-01 20:19:35.165 [1/start/2 (pid 96712)] 
2020-07-01 20:19:35.165 [1/start/2 (pid 96712)] Using metadata provider: service@https://jhh68z17uf.execute-api.ap-southeast-2.amazonaws.com/api/
2020-07-01 20:19:35.165 [1/start/2 (pid 96712)] 
2020-07-01 20:19:35.165 [1/start/2 (pid 96712)] The start step is running locally. Next, the
2020-07-01 20:19:35.165 [1/start/2 (pid 96712)] 'hello' step will run remotely on AWS batch.
2020-07-01 20:19:35.165 [1/start/2 (pid 96712)] If you are running in the Netflix sandbox,
2020-07-01 20:19:35.165 [1/start/2 (pid 96712)] it may take some time to acquire a compute resource.
2020-07-01 20:19:35.770 [1/start/2 (pid 96712)] Task finished successfully.
2020-07-01 20:19:36.333 [1/hello/3 (pid 96718)] Task is starting.
2020-07-01 20:19:37.440 [1/hello/3 (pid 96718)] [a8390b92-fb64-49e3-babc-2ce00ce29be3] Task is starting (status SUBMITTED)...
2020-07-01 20:19:40.712 [1/hello/3 (pid 96718)] [a8390b92-fb64-49e3-babc-2ce00ce29be3] Task is starting (status RUNNABLE)...
2020-07-01 20:19:46.181 [1/hello/3 (pid 96718)] [a8390b92-fb64-49e3-babc-2ce00ce29be3] Task is starting (status STARTING)...
2020-07-01 20:20:09.134 [1/hello/3 (pid 96718)] [a8390b92-fb64-49e3-babc-2ce00ce29be3] Task is starting (status RUNNING)...
2020-07-01 20:20:12.561 [1/hello/3 (pid 96718)] [a8390b92-fb64-49e3-babc-2ce00ce29be3] Setting up task environment.
2020-07-01 20:20:25.861 [1/hello/3 (pid 96718)] [a8390b92-fb64-49e3-babc-2ce00ce29be3] Downloading code package.
2020-07-01 20:20:25.861 [1/hello/3 (pid 96718)] [a8390b92-fb64-49e3-babc-2ce00ce29be3] Code package downloaded.
2020-07-01 20:20:25.861 [1/hello/3 (pid 96718)] [a8390b92-fb64-49e3-babc-2ce00ce29be3] Task is starting.
2020-07-01 20:20:28.039 [1/hello/3 (pid 96718)] [a8390b92-fb64-49e3-babc-2ce00ce29be3] Metaflow says: Hi from AWS!
2020-07-01 20:20:28.039 [1/hello/3 (pid 96718)] [a8390b92-fb64-49e3-babc-2ce00ce29be3] Task finished with exit code 0.
2020-07-01 20:20:28.789 [1/hello/3 (pid 96718)] Task finished successfully.
2020-07-01 20:20:29.152 [1/end/4 (pid 96816)] Task is starting.
2020-07-01 20:20:30.867 [1/end/4 (pid 96816)] HelloAWS is finished.
2020-07-01 20:20:31.526 [1/end/4 (pid 96816)] Task finished successfully.
2020-07-01 20:20:31.626 Done!
```

## Request

Please update test [Episode 6: Statistics Redux](https://docs.metaflow.org/getting-started/tutorials/season-2-scaling-out-and-up/episode06) to verify if it actually works, and update to reflect fixes as those in https://github.com/Netflix/metaflow/issues/95.

**Comment by savingoyal** [comment]
@oonisim Here are the instructions to properly install conda - https://docs.conda.io/en/latest/miniconda.html. 
We will change the tutorial to ensure that `@conda_base(libraries={'pandas' : '...'}, python='...')` is present by default.

**Comment by oonisim** [comment]
Switched to conda. This looks to be a known issue as in [conda update permission error #3448](https://github.com/conda/conda/issues/3448).

```
$ python 02-statistics/stats.py --with batch --environment=conda  run --max-workers 4
	Metaflow 2.0.5 executing MovieStatsFlow for user:user
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint not found, so extra checks are disabled.
2020-07-01 21:49:36.311 Bootstrapping conda environment...(this could take a few minutes)
    Internal error
Traceback (most recent call last):
  File "/Users/user/.local/lib/python3.7/site-packages/metaflow/cli.py", line 857, in main
    start(auto_envvar_prefix='METAFLOW', obj=state)
  File "/Users/user/.conda/envs/metaflow/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(args, kwargs)
  File "/Users/user/.conda/envs/metaflow/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/user/.conda/envs/metaflow/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/.conda/envs/metaflow/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/Users/user/.conda/envs/metaflow/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(args, kwargs)
  File "/Users/user/.local/lib/python3.7/site-packages/metaflow/cli.py", line 510, in wrapper
    return func(args, kwargs)
  File "/Users/user/.conda/envs/metaflow/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, args, kwargs)
  File "/Users/user/.local/lib/python3.7/site-packages/metaflow/cli.py", line 591, in run
    before_run(obj, tags, decospecs + obj.environment.decospecs())
  File "/Users/user/.local/lib/python3.7/site-packages/metaflow/cli.py", line 647, in before_run
    obj.package = MetaflowPackage(obj.flow, obj.environment, obj.logger, obj.package_suffixes)
  File "/Users/user/.local/lib/python3.7/site-packages/metaflow/package.py", line 33, in __init__
    environment)
  File "/Users/user/.local/lib/python3.7/site-packages/metaflow/plugins/conda/conda_step_decorator.py", line 215, in package_init
    self._prepare_step_environment(step, self.local_root)
  File "/Users/user/.local/lib/python3.7/site-packages/metaflow/plugins/conda/conda_step_decorator.py", line 165, in _prepare_step_environment
    env_id = self._resolve_step_environment(ds_root)
  File "/Users/user/.local/lib/python3.7/site-packages/metaflow/plugins/conda/conda_step_decorator.py", line 115, in _resolve_step_environment
    self.conda.create(self.step, env_id, deps, architecture=self.architecture)
  File "/Users/user/.local/lib/python3.7/site-packages/metaflow/plugins/conda/conda.py", line 47, in create
    with CondaLock(self._env_lock_file(env_id)):
  File "/Users/user/.local/lib/python3.7/site-packages/metaflow/plugins/conda/conda.py", line 213, in __enter__
    self._acquire()
  File "/Users/user/.local/lib/python3.7/site-packages/metaflow/plugins/conda/conda.py", line 191, in _acquire
    os.O_EXCL | os.O_RDWR)
PermissionError: [Errno 13] Permission denied: '/opt/anaconda3/mf_env-creation.lock'
```
