### ISSUE TITLE
Conda environment bin directory not in PATH for conda steps

### ISSUE THREAD

**Issue by hajapy** [Netflix/metaflow#302]
When exploring possible uses for metaflow, I ran into unexpected behaviour with conda steps whereby subprocess calls to commands I'd expect to be available (as if the conda env were active) would fail. This minimal example shows a reproduction as well as a workaround.

<details>
  <summary>Contents of ffmpeg.py</summary>

```
import subprocess
import os
import sys
from functools import wraps

from metaflow import FlowSpec, step, conda, conda_base


def conda_bin_path_decorator(f):
    @wraps(f)
    def wrapper(*args, **kwds):
        bin_dir = os.path.join(sys.exec_prefix, 'bin')
        old = os.environ.get('PATH')
        os.environ['PATH'] = bin_dir + os.pathsep + (old or '')
        try:
            return f(*args, **kwds)
        finally:
            if old is None:
                del os.environ['PATH']
            else:
                os.environ['PATH'] = old
    return wrapper


@conda_base(python='3.8.4', libraries={'boto3': '1.14.47', 'click': '7.1.2', 'requests': '2.24.0', 'coverage': '5.2.1'})
class FFMpegFlow(FlowSpec):
    """
    Example flow
    """
    @conda(libraries={'ffmpeg': '4.3.1'})
    @step
    def start(self):
        """
        Determine ffmpeg version
        """
        self.ffmpeg_which = subprocess.check_output(['which', 'ffmpeg']).decode()
        self.ffmpeg_version = subprocess.check_output(['ffmpeg', '-version']).decode()
        print(self.ffmpeg_which)
        print(self.ffmpeg_version)
        self.next(self.end)

    @conda(disabled=True)
    @step
    def end(self):
        """
        The end.
        """
        print("end")


if __name__ == '__main__':
    FFMpegFlow()
```
</details>

<details>
  <summary>Running this command generates this output</summary>

```
❯ CONDA_CHANNELS=conda-forge python ffmpeg.py --environment=conda run
Metaflow 2.2.2 executing FFMpegFlow for user:andrew
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
2020-08-23 14:54:32.889 Bootstrapping conda environment...(this could take a few minutes)
2020-08-23 14:54:34.518 Workflow starting (run-id 1598208874512993):
2020-08-23 14:54:35.341 [1598208874512993/start/1 (pid 47515)] Task is starting.
2020-08-23 14:54:35.675 [1598208874512993/start/1 (pid 47515)] <flow FFMpegFlow step start> failed:
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]     Internal error
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)] Traceback (most recent call last):
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]   File "/tmp/tmppfe3jjqy/metaflow/cli.py", line 883, in main
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]     start(auto_envvar_prefix='METAFLOW', obj=state)
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]   File "/Users/andrew/miniconda3/envs/metaflow_FFMpegFlow_osx-64_eda4fdb429ee6f1e9fc77800c944948b4508d386/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]     return self.main(args, kwargs)
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]   File "/Users/andrew/miniconda3/envs/metaflow_FFMpegFlow_osx-64_eda4fdb429ee6f1e9fc77800c944948b4508d386/lib/python3.8/site-packages/click/core.py", line 782, in main
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]     rv = self.invoke(ctx)
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]   File "/Users/andrew/miniconda3/envs/metaflow_FFMpegFlow_osx-64_eda4fdb429ee6f1e9fc77800c944948b4508d386/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]     return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]   File "/Users/andrew/miniconda3/envs/metaflow_FFMpegFlow_osx-64_eda4fdb429ee6f1e9fc77800c944948b4508d386/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]     return ctx.invoke(self.callback, ctx.params)
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]   File "/Users/andrew/miniconda3/envs/metaflow_FFMpegFlow_osx-64_eda4fdb429ee6f1e9fc77800c944948b4508d386/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]     return callback(args, kwargs)
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]   File "/Users/andrew/miniconda3/envs/metaflow_FFMpegFlow_osx-64_eda4fdb429ee6f1e9fc77800c944948b4508d386/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
2020-08-23 14:54:35.676 [1598208874512993/start/1 (pid 47515)]     return f(get_current_context().obj, args, kwargs)
2020-08-23 14:54:35.677 [1598208874512993/start/1 (pid 47515)]   File "/tmp/tmppfe3jjqy/metaflow/cli.py", line 437, in step
2020-08-23 14:54:35.677 [1598208874512993/start/1 (pid 47515)]     task.run_step(step_name,
2020-08-23 14:54:35.677 [1598208874512993/start/1 (pid 47515)]   File "/tmp/tmppfe3jjqy/metaflow/task.py", line 394, in run_step
2020-08-23 14:54:35.677 [1598208874512993/start/1 (pid 47515)]     self._exec_step_function(step_func)
2020-08-23 14:54:35.677 [1598208874512993/start/1 (pid 47515)]   File "/tmp/tmppfe3jjqy/metaflow/task.py", line 47, in _exec_step_function
2020-08-23 14:54:35.677 [1598208874512993/start/1 (pid 47515)]     step_function()
2020-08-23 14:54:35.677 [1598208874512993/start/1 (pid 47515)]   File "ffmpeg.py", line 36, in start
2020-08-23 14:54:35.677 [1598208874512993/start/1 (pid 47515)]     self.ffmpeg_which = subprocess.check_output(['which', 'ffmpeg']).decode()
2020-08-23 14:54:35.677 [1598208874512993/start/1 (pid 47515)]   File "/Users/andrew/miniconda3/envs/metaflow_FFMpegFlow_osx-64_eda4fdb429ee6f1e9fc77800c944948b4508d386/lib/python3.8/subprocess.py", line 411, in check_output
2020-08-23 14:54:35.677 [1598208874512993/start/1 (pid 47515)]     return run(popenargs, stdout=PIPE, timeout=timeout, check=True,
2020-08-23 14:54:35.724 [1598208874512993/start/1 (pid 47515)]   File "/Users/andrew/miniconda3/envs/metaflow_FFMpegFlow_osx-64_eda4fdb429ee6f1e9fc77800c944948b4508d386/lib/python3.8/subprocess.py", line 512, in run
2020-08-23 14:54:35.724 [1598208874512993/start/1 (pid 47515)]     raise CalledProcessError(retcode, process.args,
2020-08-23 14:54:35.724 [1598208874512993/start/1 (pid 47515)] subprocess.CalledProcessError: Command '['which', 'ffmpeg']' returned non-zero exit status 1.
2020-08-23 14:54:35.724 [1598208874512993/start/1 (pid 47515)]
2020-08-23 14:54:35.726 [1598208874512993/start/1 (pid 47515)] Task failed.
2020-08-23 14:54:35.726 Workflow failed.
2020-08-23 14:54:35.727 Terminating 0 active tasks...
2020-08-23 14:54:35.727 Flushing logs...
    Step failure:
    Step start (task-id 1) failed.
```
</details>

<details>
  <summary>If I instead decorate step with the provided `conda_bin_path_decorator`, the flow succeeds.
</summary>

```
❯ CONDA_CHANNELS=conda-forge python ffmpeg.py --environment=conda run
Metaflow 2.2.2 executing FFMpegFlow for user:andrew
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
2020-08-23 14:53:46.186 Bootstrapping conda environment...(this could take a few minutes)
2020-08-23 14:54:09.638 Workflow starting (run-id 1598208849632252):
2020-08-23 14:54:10.582 [1598208849632252/start/1 (pid 47211)] Task is starting.
2020-08-23 14:54:16.766 [1598208849632252/start/1 (pid 47211)] /Users/andrew/miniconda3/envs/metaflow_FFMpegFlow_osx-64_eda4fdb429ee6f1e9fc77800c944948b4508d386/bin/ffmpeg
2020-08-23 14:54:16.817 [1598208849632252/start/1 (pid 47211)]
2020-08-23 14:54:16.817 [1598208849632252/start/1 (pid 47211)] ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
2020-08-23 14:54:16.817 [1598208849632252/start/1 (pid 47211)] built with clang version 10.0.1
2020-08-23 14:54:16.817 [1598208849632252/start/1 (pid 47211)] configuration: --prefix=/Users/andrew/miniconda3/envs/metaflow_FFMpegFlow_osx-64_eda4fdb429ee6f1e9fc77800c944948b4508d386 --cc=x86_64-apple-darwin13.4.0-clang --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame
2020-08-23 14:54:16.817 [1598208849632252/start/1 (pid 47211)] libavutil      56. 51.100 / 56. 51.100
2020-08-23 14:54:16.817 [1598208849632252/start/1 (pid 47211)] libavcodec     58. 91.100 / 58. 91.100
2020-08-23 14:54:16.817 [1598208849632252/start/1 (pid 47211)] libavformat    58. 45.100 / 58. 45.100
2020-08-23 14:54:16.817 [1598208849632252/start/1 (pid 47211)] libavdevice    58. 10.100 / 58. 10.100
2020-08-23 14:54:16.818 [1598208849632252/start/1 (pid 47211)] libavfilter     7. 85.100 /  7. 85.100
2020-08-23 14:54:16.818 [1598208849632252/start/1 (pid 47211)] libavresample   4.  0.  0 /  4.  0.  0
2020-08-23 14:54:16.818 [1598208849632252/start/1 (pid 47211)] libswscale      5.  7.100 /  5.  7.100
2020-08-23 14:54:16.818 [1598208849632252/start/1 (pid 47211)] libswresample   3.  7.100 /  3.  7.100
2020-08-23 14:54:16.818 [1598208849632252/start/1 (pid 47211)] libpostproc    55.  7.100 / 55.  7.100
2020-08-23 14:54:16.818 [1598208849632252/start/1 (pid 47211)]
2020-08-23 14:54:16.821 [1598208849632252/start/1 (pid 47211)] Task finished successfully.
2020-08-23 14:54:16.826 [1598208849632252/end/2 (pid 47257)] Task is starting.
2020-08-23 14:54:17.365 [1598208849632252/end/2 (pid 47257)] end
2020-08-23 14:54:17.415 [1598208849632252/end/2 (pid 47257)] Task finished successfully.
2020-08-23 14:54:17.416 Done!
```
</details>

So, my question is should this be handled already by the metaflow conda decorator or should we be doing this extra PATH manipulation ourselves if we need access to entrypoints / cli commands that we might want to call through subprocess?

**Comment by savingoyal** [comment]
Good point! We should add this in. @jasonge27 can you take care of this?

**Comment by jasonge27** [comment]
Thanks for reporting the issue! As a quick workaround, you can use `ffmpeg_path = os.path.join(os.path.dirname(sys.executable), 'ffmpeg')` to specify the right executable inside a conda step. 

I am a bit hesitant to change the PATH env variable for the whole step as it may have other unintended side effects. As least it could break backward compatibility with some existing metaflow projects. We will figure out a better solution in a future release.

The following code works on my computer:
```
import subprocess
import os
import sys
from functools import wraps

from metaflow import FlowSpec, step, conda, conda_base

@conda_base(python='3.8.4', libraries={'boto3': '1.14.47', 'click': '7.1.2', 'requests': '2.24.0', 'coverage': '5.2.1'})
class FFMpegFlow(FlowSpec):
    """
    Example flow
    """
    @conda(libraries={'ffmpeg': '4.3.1'})
    @step
    def start(self):
        """
        Determine ffmpeg version
        """
        ffmpeg_path = os.path.join(os.path.dirname(sys.executable), 'ffmpeg')
        self.ffmpeg_version = subprocess.check_output([ffmpeg_path, '-version']).decode()
        print(self.ffmpeg_version)
        self.next(self.end)

    @conda(disabled=True)
    @step
    def end(self):
        """
        The end.
        """
        print("end")


if __name__ == '__main__':
    FFMpegFlow()
```

**Comment by hajapy** [comment]
That’s ultimately fine with me. Since I can easily write such a decorator or use the explicit form this isn’t a blocker. It may be useful to have an example or documentation for this, as a new user it took a bit of investigation to understand what was going on.

I would caution though that any projects that would break due to this are likely already erroneously calling a system executable that may be in both the conda env and the system PATH.

A non breaking solution might be a flag on the conda decorator to opt in to this behavior? (With future plans to make it default?)

(Also please note the conda deco logic above was just a hack and is not as robust as we may want since it assumes no changes to PATH occurs within the inner call, which may be wrong.)

**Comment by jasonge27** [comment]
Thank you @hajapy for the comments. We decide to add conda bin path to PATH in conda steps. Here's the PR https://github.com/Netflix/metaflow/pull/307. It will come out in the next release.

**Comment by hajapy** [comment]
@jasonge27 I have run into an issue with the solution, in that it does not seem to work when executing in batch. I think the problem is that the block is conditional on not being run within a batch context:

https://github.com/Netflix/metaflow/blob/46a3a8e6804300f639e12946b50cca4fa5efe23b/metaflow/plugins/conda/conda_step_decorator.py#L229-L242

Do you have a recommended approach to addressing this? I can work around it with my above solution, but it seems perhaps this is not as fixed as was thought.
