### ISSUE TITLE
Flow fails because `IncludeFile`'s  default value for the `help` argument is None

### ISSUE THREAD

**Issue by denismaciel** [Netflix/metaflow#305]
Hi, 

I am running `metaflow==2.2.2` with Python 3.7 and I guess I found a bug.

When running the code below with `python3 pipeline_bug.py run`, 

```python
# pipeline_bug.py
from metaflow import FlowSpec, step, IncludeFile


class TestFlow(FlowSpec):

    a = IncludeFile("a", default="a.txt")

    @step
    def start(self):

        self.next(self.end)

    @step
    def end(self):
        ...


if __name__ == "__main__":
    TestFlow()
```

I get the error message:

```
$ python pipeline_bug.py run
Traceback (most recent call last):
  File "pipeline_bug.py", line 19, in <module>
    TestFlow()
  File "/home/denis/.pyenv/versions/pen-0/lib/python3.7/site-packages/metaflow/flowspec.py", line 77, in __init__
    from . import cli
  File "/home/denis/.pyenv/versions/pen-0/lib/python3.7/site-packages/metaflow/cli.py", line 459, in <module>
    def init(obj, run_id=None, task_id=None, **kwargs):
  File "/home/denis/.pyenv/versions/pen-0/lib/python3.7/site-packages/metaflow/parameters.py", line 223, in wrapper
    kwargs = arg.option_kwargs(deploy_mode)
  File "/home/denis/.pyenv/versions/pen-0/lib/python3.7/site-packages/metaflow/parameters.py", line 189, in option_kwargs
    "[default: deploy-time value of '%s']" % self.name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by denismaciel** [comment]
The error happens [here](https://github.com/Netflix/metaflow/blob/master/metaflow/parameters.py#L184-L194) while calling `kwargs.get('help', '')  +  "[default: deploy-time value of '%s']" % self.name `, because for the field `help` does exists and is `None`.

**Comment by romain-intel** [comment]
Thank you for reporting this and getting to the cause. We will fix this in an upcoming release.
