### ISSUE TITLE
Trouble executing with batch using IncludeFile 

### ISSUE THREAD

**Issue by hajapy** [Netflix/metaflow#353]
I have a flow that essentially just does IncludeFile() twice. 

```
class SomeFlow(FlowSpec):
    file1 = IncludeFile(
        "file1",
        required=True,
        is_text=False,
    )
    file2 = IncludeFile(
        "file2",
        required=True,
        is_text=False,
    )

    @batch
    @step
    def start(self):
        print(self.file1)
        print(self.file2)
        self.next(self.end)

    @step
    def end(self):
        print('end')
```

I try to trigger this with `python some_flow.py run --file1 file1.json --file2 s3://my-bucket/file2.json`.

This gives the following stacktrace:

```
Metaflow 2.2.3 executing SomeFlow for user:aachkar
    Internal error
Traceback (most recent call last):
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/metaflow/cli.py", line 883, in main
    start(auto_envvar_prefix='METAFLOW', obj=state)
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(args, kwargs)
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/click/core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/click/core.py", line 1965, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/click/core.py", line 1589, in full_process_value
    value = self.process_value(ctx, value)
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/click/core.py", line 1579, in process_value
    return self.type_cast_value(ctx, value)
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/click/core.py", line 1568, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/click/core.py", line 1565, in _convert
    return self.type(value, self, ctx)
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/click/types.py", line 46, in __call__
    return self.convert(value, param, ctx)
  File "/Users/aachkar/Library/Caches/pypoetry/virtualenvs/cv-workflows-rEYCzLQU-py3.8/lib/python3.8/site-packages/metaflow/includefile.py", line 229, in convert
    param_ctx = context_proto._replace(parameter_name=self.parameter_name)
AttributeError: 'NoneType' object has no attribute '_replace'
```

This fails if I make both files local file paths, one an s3 path and the other a local file path, but it works if both are s3 paths.

**Comment by savingoyal** [comment]
Yes, we have a PR out for this issue. We will be making a new release of Metaflow soon.
