### ISSUE TITLE
IncludeFile(..., required=False) doesn't seem to work

### ISSUE THREAD

**Issue by peterwilton-ttam** [Netflix/metaflow#418]
With Metaflow 2.2.5 and Python 3.8.6, the following doesn't work if I don't specify `--test_file` at the command line:

``` python
from metaflow import FlowSpec, IncludeFile, step

class TestFlow(FlowSpec):

    file_bytes = IncludeFile(
        'test_file',
        is_text=False,
        required=False)

    @step
    def start(self):
        self.file_bytes
        self.next(self.end)

    @step
    def end(self):
        pass

if __name__ == '__main__':
    TestFlow()
```

The following error is raised:

```
Metaflow 2.2.5 executing TestFlow for user:user
Validating your flow...
    The graph looks good!
2021-01-14 13:49:54.415 Workflow starting (run-id 1610660994326268):
2021-01-14 13:49:54.455 [1610660994326268/start/1 (pid 9281)] Task is starting.
2021-01-14 13:49:54.806 [1610660994326268/start/1 (pid 9281)] <flow TestFlow step start> failed:
2021-01-14 13:49:54.895 [1610660994326268/start/1 (pid 9281)]     Internal error
2021-01-14 13:49:54.896 [1610660994326268/start/1 (pid 9281)] Traceback (most recent call last):
2021-01-14 13:49:54.897 [1610660994326268/start/1 (pid 9281)]   File "/usr/local/lib/python3.8/site-packages/metaflow/cli.py", line 916, in main
2021-01-14 13:49:54.898 [1610660994326268/start/1 (pid 9281)]     start(auto_envvar_prefix='METAFLOW', obj=state)
2021-01-14 13:49:54.898 [1610660994326268/start/1 (pid 9281)]   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2021-01-14 13:49:54.899 [1610660994326268/start/1 (pid 9281)]     return self.main(args, kwargs)
2021-01-14 13:49:54.900 [1610660994326268/start/1 (pid 9281)]   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
2021-01-14 13:49:54.901 [1610660994326268/start/1 (pid 9281)]     rv = self.invoke(ctx)
2021-01-14 13:49:54.902 [1610660994326268/start/1 (pid 9281)]   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
2021-01-14 13:49:54.902 [1610660994326268/start/1 (pid 9281)]     return _process_result(sub_ctx.command.invoke(sub_ctx))
2021-01-14 13:49:54.903 [1610660994326268/start/1 (pid 9281)]   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2021-01-14 13:49:54.904 [1610660994326268/start/1 (pid 9281)]     return ctx.invoke(self.callback, ctx.params)
2021-01-14 13:49:54.963 [1610660994326268/start/1 (pid 9281)]   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2021-01-14 13:49:54.963 [1610660994326268/start/1 (pid 9281)]     return callback(args, kwargs)
2021-01-14 13:49:54.964 [1610660994326268/start/1 (pid 9281)]   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
2021-01-14 13:49:54.964 [1610660994326268/start/1 (pid 9281)]     return f(get_current_context().obj, args, kwargs)
2021-01-14 13:49:54.965 [1610660994326268/start/1 (pid 9281)]   File "/usr/local/lib/python3.8/site-packages/metaflow/cli.py", line 436, in step
2021-01-14 13:49:54.966 [1610660994326268/start/1 (pid 9281)]     task.run_step(step_name,
2021-01-14 13:49:54.966 [1610660994326268/start/1 (pid 9281)]   File "/usr/local/lib/python3.8/site-packages/metaflow/task.py", line 396, in run_step
2021-01-14 13:49:54.967 [1610660994326268/start/1 (pid 9281)]     self._exec_step_function(step_func)
2021-01-14 13:49:54.967 [1610660994326268/start/1 (pid 9281)]   File "/usr/local/lib/python3.8/site-packages/metaflow/task.py", line 47, in _exec_step_function
2021-01-14 13:49:54.968 [1610660994326268/start/1 (pid 9281)]     step_function()
2021-01-14 13:49:54.968 [1610660994326268/start/1 (pid 9281)]   File "includefile_flow.py", line 12, in start
2021-01-14 13:49:54.968 [1610660994326268/start/1 (pid 9281)]     self.file_bytes
2021-01-14 13:49:54.969 [1610660994326268/start/1 (pid 9281)]   File "/usr/local/lib/python3.8/site-packages/metaflow/flowspec.py", line 125, in __getattr__
2021-01-14 13:49:54.969 [1610660994326268/start/1 (pid 9281)]     setattr(self, name, x)
2021-01-14 13:49:54.970 [1610660994326268/start/1 (pid 9281)] AttributeError: can't set attribute
2021-01-14 13:49:54.970 [1610660994326268/start/1 (pid 9281)]
2021-01-14 13:49:55.002 [1610660994326268/start/1 (pid 9281)] Task failed.
2021-01-14 13:49:55.002 Workflow failed.
2021-01-14 13:49:55.002 Terminating 0 active tasks...
2021-01-14 13:49:55.002 Flushing logs...
    Step failure:
    Step start (task-id 1) failed.
```

This is with a local datastore — I haven't tried it with S3. I guess I'd expect it to be `None` or `b''` when not provided.

**Comment by peterwilton-ttam** [comment]
It [looks like](https://github.com/Netflix/metaflow/pull/413) the datastore code is about to be replaced, but I did identify a fix for this problem by commenting out `IncludeFile.__getattr__`. The problem seems to be with `IncludeFile.load_parameter`, which, unlike `Parameter.load_parameter`, doesn't tolerate `val=None`. This seems to fix it:

```
diff --git a/metaflow/includefile.py b/metaflow/includefile.py
index 62b8703..be88471 100644
--- a/metaflow/includefile.py
+++ b/metaflow/includefile.py
@@ -267,6 +267,8 @@ class IncludeFile(Parameter):
             type=FilePathClass(is_text, encoding), **kwargs)

     def load_parameter(self, val):
+        if val is None:
+            return val
         ok, file_type, err = LocalFile.is_file_handled(val)
         if not ok:
             raise MetaflowException("Parameter '%s' could not be loaded: %s" % (self.name, err))
```

**Comment by romain-intel** [comment]
Thanks for the suggestion @peterwilton-ttam. I'll integrate your fix and it will go out in the next release. Thanks for catching this.
