### ISSUE TITLE
join step with merge_artifacts fails ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by BartBaddeley** [Netflix/metaflow#599]
I have a join step that does nothing apart from calling  merge_artifacts() which fails with a ModuleNotFoundError: No module named 'numpy'. Is this expected behaviour?

    @step
    def join(self, inputs) -> None: 
        self.merge_artifacts(inputs)
        self.next(self.end)

2021-07-02 11:03:14.761 [1625219729083955/join/37 (pid 7562)] Task is starting.
2021-07-02 11:03:15.707 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] Task is starting (status SUBMITTED)...
2021-07-02 11:03:21.012 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] Task is starting (status RUNNABLE)...
2021-07-02 11:03:22.068 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] Task is starting (status STARTING)...
2021-07-02 11:03:26.272 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] Task is starting (status RUNNING)...
2021-07-02 11:03:25.308 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] Setting up task environment.
2021-07-02 11:03:35.016 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] Downloading code package...
2021-07-02 11:03:35.683 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] Code package downloaded.
2021-07-02 11:03:35.695 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] Task is starting.
2021-07-02 11:03:35.697 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] Bootstrapping environment...
2021-07-02 11:03:55.414 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] Environment bootstrapped.
2021-07-02 11:04:05.582 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] <flow CreateVectorsParquet step join> failed:
2021-07-02 11:04:05.966 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     Internal error
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] Traceback (most recent call last):
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow/cli.py", line 987, in main
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     start(auto_envvar_prefix='METAFLOW', obj=state)
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow_CreateVectorsParquet_linux-64_ca715aa2977fc3e5ef3c38d469289174ee8554eb/lib/python3.7/site-packages/click/core.py", line 829, in __call__
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     return self.main(args, kwargs)
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow_CreateVectorsParquet_linux-64_ca715aa2977fc3e5ef3c38d469289174ee8554eb/lib/python3.7/site-packages/click/core.py", line 782, in main
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     rv = self.invoke(ctx)
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow_CreateVectorsParquet_linux-64_ca715aa2977fc3e5ef3c38d469289174ee8554eb/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     return _process_result(sub_ctx.command.invoke(sub_ctx))
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow_CreateVectorsParquet_linux-64_ca715aa2977fc3e5ef3c38d469289174ee8554eb/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     return ctx.invoke(self.callback, ctx.params)
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow_CreateVectorsParquet_linux-64_ca715aa2977fc3e5ef3c38d469289174ee8554eb/lib/python3.7/site-packages/click/core.py", line 610, in invoke
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     return callback(args, kwargs)
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow_CreateVectorsParquet_linux-64_ca715aa2977fc3e5ef3c38d469289174ee8554eb/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     return f(get_current_context().obj, args, kwargs)
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow/cli.py", line 504, in step
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     max_user_code_retries)
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow/task.py", line 391, in run_step
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     self._exec_step_function(step_func, input_obj)
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow/task.py", line 49, in _exec_step_function
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     step_function(input_obj)
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "create_vectors_parquet.py", line 247, in join
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     self.merge_artifacts(inputs)
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow/flowspec.py", line 356, in merge_artifacts
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     setattr(self, var, getattr(inp, var))
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow/flowspec.py", line 123, in __getattr__
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     x = self._datastore[name]
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow/datastore/datastore.py", line 590, in __getitem__
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     return self._load_object(self.objects[var])
2021-07-02 11:04:09.815 [1625219729083955/join/37 (pid 7562)] AWS Batch error:
2021-07-02 11:04:09.816 [1625219729083955/join/37 (pid 7562)] Essential container in task exited This could be a transient error. Use @retry to retry.
2021-07-02 11:04:09.955 [1625219729083955/join/37 (pid 7562)] 
2021-07-02 11:04:05.967 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]   File "/metaflow/metaflow/datastore/datastore.py", line 477, in _load_object
2021-07-02 11:04:05.968 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297]     return pickle.loads(blob)
2021-07-02 11:04:05.968 [1625219729083955/join/37 (pid 7562)] [28aca189-adaf-407d-94ec-0720b5d06297] ModuleNotFoundError: No module named 'numpy'

**Comment by oavdeev** [comment]
Do earlier steps depend on numpy? You could get an error like this if one of the earlier steps produces a numpy matrix and stores it as an artifact. Artifacts are serialized using pickle, which supports storing almost arbitrary python objects, however the class has to be available to the Python interpreter at the time when you unpickle the artifact.

Can you share how the entire flow looks like we could check if that's indeed the case here? Also, what do you use to manage dependencies? `@conda` or something else?

**Comment by romain-intel** [comment]
Also, I believe (based on the traceback) that you are on an older version of Metaflow. Please upgrade to 2.3.1 or later. I suspect this problem will go away at that point.

**Comment by BartBaddeley** [comment]
@oavdeev Earlier steps do indeed depend on numpy and I can confirm that we are using @conda for managing dependencies. 

@romain-intel the current version of metaflow is 2.3.0, I will upgrade and see if it helps. In the meantime I'll just change the code to handle the requirement for numpy. This error is at the end of a Flow where I'm simply joining and ending the flow to tidy things up so it is not crucial.
