### ISSUE TITLE
Questions: Consume yaml configuration files in Metaflow 

### ISSUE THREAD

**Issue by zexuan-zhou** [Netflix/metaflow#670]
I'm trying to use [dynaconf](https://www.dynaconf.com/) as my configuration management tool and I'm trying to use it in Metaflow. I have some yaml files (that are hierarchical) as my config files and dynaconf can construct a python configuration object out of those files and I'd like to import this object in Metaflow. 
When I try to submit my flow to AWS Batch, it fails because I'm not uploading the yaml config files. I know Metaflow has the `IncludeFile` functionality to include files with the flow. I wonder what's a good practice if I have many files and they follow a hierarchical config setting.

## Code to run in AWS Batch with failed result
Here is some simple code with only one yaml config file
`cat default_config/config.yaml `
```
A:
  a: a_value
  b:
    bb: bb_value
    ba: "@format {this.A.a}"
  c:
    cc: "@format {this.A.b}"
B:
  a:
    a1:
      - ["a11", "a12"]
      - ["a13", "a14"]
  b: "@jinja {{this.B.a.a1|map(attribute=0)|list}}"
```
`cat default_config/__init__.py `
```
from dynaconf import Dynaconf
import json

default_config = Dynaconf(
    settings_files=[
        'config.yaml',  # default config
    ],
)

print(f"default_config: {json.dumps(default_config.as_dict(), indent=2)}")
print(f"default_config.A.c.cc: {default_config.A.c.cc}")
print(f"type(default_config.B.b): {type(default_config.B.b)}")
```
`cat test_metaflow.py`
```
from metaflow import FlowSpec, step, batch, conda_base


@conda_base(
    libraries={
        "dynaconf": "3.1.5",
        "jinja2": "3.0.1",
    },
    python="3.7.10",
)
class TestMetaflow(FlowSpec):

    @batch
    @step
    def start(self):
        print("defualt_config:")
        from default_config import default_config
        self.next(self.end)

    @batch
    @step
    def end(self):
        print("End")


if __name__ == "__main__":
    TestMetaflow()
```
Command to run my Metaflow flow in AWS Batch (since I used the `@batch` decorator) 
`python test_metaflow.py --environment=conda run`
Failed result (this is expected as the yaml config file is not included when flow is submitted to AWS Batch
```
2021-08-24 17:20:58.370 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182] default_config: {}
2021-08-24 17:20:58.370 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182] <flow TestMetaflow step start> failed:
2021-08-24 17:20:58.824 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     Internal error
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182] Traceback (most recent call last):
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/metaflow/cli.py", line 1005, in main
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     start(auto_envvar_prefix='METAFLOW', obj=state)
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/metaflow_TestMetaflow_linux-64_ac65b9b4148b4d2809cd230fe70da329cb139d88/lib/python3.7/site-packages/click/core.py", line 829, in __call__
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     return self.main(args, kwargs)
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/metaflow_TestMetaflow_linux-64_ac65b9b4148b4d2809cd230fe70da329cb139d88/lib/python3.7/site-packages/click/core.py", line 782, in main
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     rv = self.invoke(ctx)
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/metaflow_TestMetaflow_linux-64_ac65b9b4148b4d2809cd230fe70da329cb139d88/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     return _process_result(sub_ctx.command.invoke(sub_ctx))
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/metaflow_TestMetaflow_linux-64_ac65b9b4148b4d2809cd230fe70da329cb139d88/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     return ctx.invoke(self.callback, ctx.params)
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/metaflow_TestMetaflow_linux-64_ac65b9b4148b4d2809cd230fe70da329cb139d88/lib/python3.7/site-packages/click/core.py", line 610, in invoke
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     return callback(args, kwargs)
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/metaflow_TestMetaflow_linux-64_ac65b9b4148b4d2809cd230fe70da329cb139d88/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     return f(get_current_context(), args, kwargs)
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/metaflow/cli.py", line 521, in step
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     max_user_code_retries)
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/metaflow/task.py", line 444, in run_step
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     self._exec_step_function(step_func)
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/metaflow/task.py", line 51, in _exec_step_function
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     step_function()
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "test_metaflow.py", line 17, in start
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     from default_config import default_config
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/default_config/__init__.py", line 11, in <module>
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     print(f"default_config.A.c.cc: {default_config.A.c.cc}")
2021-08-24 17:21:04.547 [947/start/15793 (pid 73517)] AWS Batch error:
2021-08-24 17:21:04.547 [947/start/15793 (pid 73517)] Essential container in task exited This could be a transient error. Use @retry to retry.
2021-08-24 17:21:04.547 [947/start/15793 (pid 73517)] 
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/metaflow_TestMetaflow_linux-64_ac65b9b4148b4d2809cd230fe70da329cb139d88/lib/python3.7/site-packages/dynaconf/base.py", line 177, in __getattr__
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     value = getattr(self._wrapped, name)
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]   File "/metaflow/metaflow_TestMetaflow_linux-64_ac65b9b4148b4d2809cd230fe70da329cb139d88/lib/python3.7/site-packages/dynaconf/base.py", line 311, in __getattribute__
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]     return super().__getattribute__(name)
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182] AttributeError: 'Settings' object has no attribute 'A'
2021-08-24 17:20:58.825 [947/start/15793 (pid 73517)] [0408766f-c28a-480e-8c91-74b6b694c182]
2021-08-24 17:21:05.436 [947/start/15793 (pid 73517)] Task failed.
2021-08-24 17:21:06.289 Workflow failed.
2021-08-24 17:21:06.289 Terminating 0 active tasks...
2021-08-24 17:21:06.289 Flushing logs...
    Step failure:
    Step start (task-id 15793) failed.

```

## Code to run locally with expected result
Comment out the `@batch` decorator
`cat test_metaflow.py`
```
from metaflow import FlowSpec, step, batch, conda_base


@conda_base(
    libraries={
        "dynaconf": "3.1.5",
        "jinja2": "3.0.1",
    },
    python="3.7.10",
)
class TestMetaflow(FlowSpec):

    # @batch
    @step
    def start(self):
        print("default_config:")
        from default_config import default_config
        self.next(self.end)

    # @batch
    @step
    def end(self):
        print("End")


if __name__ == "__main__":
    TestMetaflow()
```
and run `python test_metaflow.py --environment=conda run`
gives expected result like this
```
Bootstrapping conda environment...(this could take a few minutes)
2021-08-24 17:39:02.329 Workflow starting (run-id 1629851942322649):
2021-08-24 17:39:03.999 [1629851942322649/start/1 (pid 74482)] Task is starting.
2021-08-24 17:39:04.408 [1629851942322649/start/1 (pid 74482)] defualt_config:
2021-08-24 17:39:04.576 [1629851942322649/start/1 (pid 74482)] default_config: {
2021-08-24 17:39:04.637 [1629851942322649/start/1 (pid 74482)] "A": {
2021-08-24 17:39:04.637 [1629851942322649/start/1 (pid 74482)] "a": "a_value",
2021-08-24 17:39:04.637 [1629851942322649/start/1 (pid 74482)] "b": {
2021-08-24 17:39:04.637 [1629851942322649/start/1 (pid 74482)] "bb": "bb_value",
2021-08-24 17:39:04.637 [1629851942322649/start/1 (pid 74482)] "ba": "a_value"
2021-08-24 17:39:04.637 [1629851942322649/start/1 (pid 74482)] },
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] "c": {
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] "cc": "{'bb': 'bb_value', 'ba': 'a_value'}"
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] }
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] },
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] "B": {
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] "a": {
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] "a1": [
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] [
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] "a11",
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] "a12"
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] ],
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] [
2021-08-24 17:39:04.638 [1629851942322649/start/1 (pid 74482)] "a13",
2021-08-24 17:39:04.639 [1629851942322649/start/1 (pid 74482)] "a14"
2021-08-24 17:39:04.639 [1629851942322649/start/1 (pid 74482)] ]
2021-08-24 17:39:04.639 [1629851942322649/start/1 (pid 74482)] ]
2021-08-24 17:39:04.639 [1629851942322649/start/1 (pid 74482)] },
2021-08-24 17:39:04.639 [1629851942322649/start/1 (pid 74482)] "b": "['a11', 'a13']"
2021-08-24 17:39:04.639 [1629851942322649/start/1 (pid 74482)] }
2021-08-24 17:39:04.639 [1629851942322649/start/1 (pid 74482)] }
2021-08-24 17:39:04.641 [1629851942322649/start/1 (pid 74482)] Task finished successfully.
2021-08-24 17:39:06.286 [1629851942322649/end/2 (pid 74495)] Task is starting.
2021-08-24 17:39:06.724 [1629851942322649/end/2 (pid 74495)] End
2021-08-24 17:39:06.785 [1629851942322649/end/2 (pid 74495)] Task finished successfully.
2021-08-24 17:39:06.787 Done!
```

I wonder what you guys' thoughts are on how I should use `IncludeFile` to make this work and potentially if I have more hierarchical configuration files (some sub files overwriting top-level default files), what's the best practice to do it with `IncludeFile`. My experience so far with `IncludeFile` is that it seems store the file as a whole big json string and I need to dump it to disk one more time within the flow when my code tries to read it.

Thank you

**Comment by savingoyal** [comment]
@zexuan-zhou You can use `--package-suffixes`
```sh
python flow.py --package-suffixes=.yaml run --with batch
```

**Comment by zexuan-zhou** [comment]
@savingoyal I think that works. Thank you!
I just tried to search it in the doc but couldn't find it. 
https://docs.metaflow.org/getting-started/install?q=package-suffixes

**Comment by savingoyal** [comment]
We need to update our docsite :slightly_smiling_face:
