### ISSUE TITLE
Issue with tutorial #3

### ISSUE THREAD

**Issue by minhtuev** [Netflix/metaflow#7]
Python environment: pyenv local with Python 3.6.8

```
Metaflow 2.0.0 executing PlayListFlow for user:minhtue

The next version of our playlist generator that uses the statistics
generated from 'Episode 02' to improve the title recommendations.

The flow performs the following steps:

1) Load the genre specific statistics from the MovieStatsFlow.
2) In parallel branches:
- A) Build a playlist from the top grossing films in the requested genre.
- B) Choose a random movie.
3) Join the two to create a movie playlist and display it.

Step start
    Use the Metaflow client to retrieve the latest successful run from our
    MovieStatsFlow and assign them as data artifacts in this flow.
    => bonus_movie, genre_movies

Step bonus_movie
    This step chooses a random title for a different movie genre.
    => join

Step genre_movies
    Select the top performing movies from the use specified genre.
    => join

Step join
    Join our parallel branches and merge results.
    => end

Step end
    Print out the playlist and bonus movie.

➜  metaflow-tutorials python 03-playlist-redux/playlist.py run
Metaflow 2.0.0 executing PlayListFlow for user:minhtue
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint not found, so extra checks are disabled.
2019-12-03 16:46:33.660 Workflow starting (run-id 1575420393649410):
2019-12-03 16:46:33.681 [1575420393649410/start/1 (pid 34515)] Task is starting.
2019-12-03 16:46:34.074 [1575420393649410/start/1 (pid 34515)] <flow PlayListFlow step start> failed:
2019-12-03 16:46:34.075 [1575420393649410/start/1 (pid 34515)] Object not found:
2019-12-03 16:46:34.075 [1575420393649410/start/1 (pid 34515)] Using metadata provider: local@/Users/minhtue/workspace/metaflow/metaflow-tutorials
2019-12-03 16:46:34.075 [1575420393649410/start/1 (pid 34515)] Flow('MovieStatsFlow') does not exist
2019-12-03 16:46:34.126 [1575420393649410/start/1 (pid 34515)]
2019-12-03 16:46:34.131 [1575420393649410/start/1 (pid 34515)] Task failed.
2019-12-03 16:46:34.131 Workflow failed.
    Step failure:
    Step start (task-id 1) failed.

**Comment by savingoyal** [comment]
@minhtuev This tutorial is supposed to be executed after `Episode 02`, since it reuses results from the previous execution. Did you execute `Episode 02`?

**Comment by seeravikiran** [comment]
You can also help us by pasting the output that you see after `metaflow status`. I suspect @savingoyal 's guess could be right.

**Comment by mpkocher** [comment]
A workaround is to copy the output of `02-statistics` workflow (e.g., `02-statistics/.metaflow` to  `03-playlist-redux/.metaflow`. Then tutorial 03 should run successfully. 

The log will show you the datastore path which I believe is used to resolve the inputs of the workflow. 

E.g., 

`2019-12-03 17:47:16.106 [1575424035526908/start/1 (pid 97015)] Using metadata provider: local@/Users/mkocher/gh_projects/metaflow/metaflow-tutorials/03-playlist-redux`

**Comment by romain-intel** [comment]
@mpkocher: yes, your workaround will work. You can also place the .metaflow folder at a common ancestor for 02-statistics and 03-playlist-redux (for example directly in metaflow-tutorials). By default, Metaflow will try to look for a .metaflow anywhere in your path hierarchy (starting in the current working directory). If it does not find one, it will create one in the current directory (you should see a message when your flow starts up that it is creating a directory). That directory contains all data artifacts and metadata (when you run locally on your laptop) and episode 3 relies on it to get results from episode 2. I hope this makes sense.

**Comment by seeravikiran** [comment]
He is running from `metaflow-tutorials` directory looking at the above invocation. I suspect therefore that 02-statistics was probably just not run.

**Comment by minhtuev** [comment]
I tried to run 02-statistics but it runs into another error:
```
➜  metaflow-tutorials python 02-statistics/stats.py run
Metaflow 2.0.0 executing MovieStatsFlow for user:minhtue
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint not found, so extra checks are disabled.
2019-12-04 13:43:04.745 Including file 02-statistics/movies.csv of size 191KB
2019-12-04 13:43:04.758 Workflow starting (run-id 1575495784736229):
2019-12-04 13:43:04.776 [1575495784736229/start/1 (pid 46310)] Task is starting.
2019-12-04 13:43:05.139 [1575495784736229/start/1 (pid 46310)] <flow MovieStatsFlow step start> failed:
2019-12-04 13:43:05.142 [1575495784736229/start/1 (pid 46310)] Internal error
2019-12-04 13:43:05.142 [1575495784736229/start/1 (pid 46310)] Traceback (most recent call last):
2019-12-04 13:43:05.142 [1575495784736229/start/1 (pid 46310)] File "/Users/minhtue/.pyenv/versions/3.6.8/lib/python3.6/site-packages/metaflow/cli.py", line 853, in main
2019-12-04 13:43:05.143 [1575495784736229/start/1 (pid 46310)] start(auto_envvar_prefix='METAFLOW', obj=state)
2019-12-04 13:43:05.143 [1575495784736229/start/1 (pid 46310)] File "/Users/minhtue/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 764, in __call__
2019-12-04 13:43:05.143 [1575495784736229/start/1 (pid 46310)] return self.main(args, kwargs)
2019-12-04 13:43:05.143 [1575495784736229/start/1 (pid 46310)] File "/Users/minhtue/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 717, in main
2019-12-04 13:43:05.143 [1575495784736229/start/1 (pid 46310)] rv = self.invoke(ctx)
2019-12-04 13:43:05.143 [1575495784736229/start/1 (pid 46310)] File "/Users/minhtue/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
2019-12-04 13:43:05.143 [1575495784736229/start/1 (pid 46310)] return _process_result(sub_ctx.command.invoke(sub_ctx))
2019-12-04 13:43:05.143 [1575495784736229/start/1 (pid 46310)] File "/Users/minhtue/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 956, in invoke
2019-12-04 13:43:05.143 [1575495784736229/start/1 (pid 46310)] return ctx.invoke(self.callback, ctx.params)
2019-12-04 13:43:05.143 [1575495784736229/start/1 (pid 46310)] File "/Users/minhtue/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 555, in invoke
2019-12-04 13:43:05.143 [1575495784736229/start/1 (pid 46310)] return callback(args, kwargs)
2019-12-04 13:43:05.144 [1575495784736229/start/1 (pid 46310)] File "/Users/minhtue/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
2019-12-04 13:43:05.144 [1575495784736229/start/1 (pid 46310)] return f(get_current_context().obj, args, kwargs)
2019-12-04 13:43:05.176 [1575495784736229/start/1 (pid 46310)] File "/Users/minhtue/.pyenv/versions/3.6.8/lib/python3.6/site-packages/metaflow/cli.py", line 430, in step
2019-12-04 13:43:05.176 [1575495784736229/start/1 (pid 46310)] max_user_code_retries)
2019-12-04 13:43:05.176 [1575495784736229/start/1 (pid 46310)] File "/Users/minhtue/.pyenv/versions/3.6.8/lib/python3.6/site-packages/metaflow/task.py", line 390, in run_step
2019-12-04 13:43:05.177 [1575495784736229/start/1 (pid 46310)] self._exec_step_function(step_func)
2019-12-04 13:43:05.177 [1575495784736229/start/1 (pid 46310)] File "/Users/minhtue/.pyenv/versions/3.6.8/lib/python3.6/site-packages/metaflow/task.py", line 47, in _exec_step_function
2019-12-04 13:43:05.177 [1575495784736229/start/1 (pid 46310)] step_function()
2019-12-04 13:43:05.177 [1575495784736229/start/1 (pid 46310)] File "02-statistics/stats.py", line 41, in start
2019-12-04 13:43:05.177 [1575495784736229/start/1 (pid 46310)] import pandas
2019-12-04 13:43:05.177 [1575495784736229/start/1 (pid 46310)] ModuleNotFoundError: No module named 'pandas'
2019-12-04 13:43:05.177 [1575495784736229/start/1 (pid 46310)]
2019-12-04 13:43:05.180 [1575495784736229/start/1 (pid 46310)] Task failed.
2019-12-04 13:43:05.180 Workflow failed.
    Step failure:
    Step start (task-id 1) failed.

**Comment by mpkocher** [comment]
@minhtuev I believe that workflow 02 requires 'pandas' installed,  Hence the error message:

`import pandas
2019-12-04 13:43:05.177 [1575495784736229/start/1 (pid 46310)] ModuleNotFoundError: No module named 'pandas'`

**Comment by seeravikiran** [comment]
Also @minhtuev you can see the pre requisite steps when you do `metaflow tutorials info <episode>`
This should tell you the pip install command to run for pandas.

**Comment by minhtuev** [comment]
Ah got it thanks
