### ISSUE TITLE
class super init causes error use_cli

### ISSUE THREAD

**Issue by mikejmills** [Netflix/metaflow#73]
`
class CompoundNetDatasetGenerator(FlowSpec):

    def __init__(self ):
        self.db_name      = "spectra_db_prod"
        self.n_comppounds = 10

        super(CompoundNetDatasetGenerator, self).__init__()
@step
    def start(self):

        #self.samples    = self.get_samples()
        self.sampleids = [1,2,3,4] #[str(id) for _,id in self.samples]

        self.next(self.get_spectra, foreach='sampleids')

    @step
    def get_spectra(self):
        #self.result = self.input
        #print("Retrieve spectra:", self.result)

        self.next(self.join)

    @step
    def join(self, inputs):
        self.next(self.end)

    @step
    def end(self):
        pass`

```
2019-12-23 22:52:12.569 [1577141526437425/join/6 (pid 17256)] <flow CompoundNetDatasetGenerator step join> failed:
2019-12-23 22:52:12.570 [1577141526437425/join/6 (pid 17256)] Internal error
2019-12-23 22:52:12.570 [1577141526437425/join/6 (pid 17256)] Traceback (most recent call last):
2019-12-23 22:52:12.866 [1577141526437425/join/6 (pid 17256)] File "/usr/local/lib/python3.6/dist-packages/metaflow/cli.py", line 853, in main
2019-12-23 22:52:12.867 [1577141526437425/join/6 (pid 17256)] start(auto_envvar_prefix='METAFLOW', obj=state)
2019-12-23 22:52:12.867 [1577141526437425/join/6 (pid 17256)] File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
2019-12-23 22:52:12.867 [1577141526437425/join/6 (pid 17256)] return self.main(args, kwargs)
2019-12-23 22:52:12.867 [1577141526437425/join/6 (pid 17256)] File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
2019-12-23 22:52:12.867 [1577141526437425/join/6 (pid 17256)] rv = self.invoke(ctx)
2019-12-23 22:52:12.867 [1577141526437425/join/6 (pid 17256)] File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
2019-12-23 22:52:12.867 [1577141526437425/join/6 (pid 17256)] return _process_result(sub_ctx.command.invoke(sub_ctx))
2019-12-23 22:52:12.867 [1577141526437425/join/6 (pid 17256)] File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
2019-12-23 22:52:12.867 [1577141526437425/join/6 (pid 17256)] return ctx.invoke(self.callback, ctx.params)
2019-12-23 22:52:12.867 [1577141526437425/join/6 (pid 17256)] File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
2019-12-23 22:52:12.867 [1577141526437425/join/6 (pid 17256)] return callback(args, kwargs)
2019-12-23 22:52:12.868 [1577141526437425/join/6 (pid 17256)] File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 27, in new_func
2019-12-23 22:52:12.868 [1577141526437425/join/6 (pid 17256)] return f(get_current_context().obj, args, kwargs)
2019-12-23 22:52:12.868 [1577141526437425/join/6 (pid 17256)] File "/usr/local/lib/python3.6/dist-packages/metaflow/cli.py", line 430, in step
2019-12-23 22:52:12.868 [1577141526437425/join/6 (pid 17256)] max_user_code_retries)
2019-12-23 22:52:12.868 [1577141526437425/join/6 (pid 17256)] File "/usr/local/lib/python3.6/dist-packages/metaflow/task.py", line 367, in run_step
2019-12-23 22:52:12.868 [1577141526437425/join/6 (pid 17256)] input_obj = Inputs(self._clone_flow(inp) for inp in inputs)
2019-12-23 22:52:12.868 [1577141526437425/join/6 (pid 17256)] File "/usr/local/lib/python3.6/dist-packages/metaflow/datastore/datastore.py", line 34, in __init__
2019-12-23 22:52:12.868 [1577141526437425/join/6 (pid 17256)] self.flows = list(flows)
2019-12-23 22:52:12.868 [1577141526437425/join/6 (pid 17256)] File "/usr/local/lib/python3.6/dist-packages/metaflow/task.py", line 367, in <genexpr>
2019-12-23 22:52:12.868 [1577141526437425/join/6 (pid 17256)] input_obj = Inputs(self._clone_flow(inp) for inp in inputs)
2019-12-23 22:52:12.868 [1577141526437425/join/6 (pid 17256)] File "/usr/local/lib/python3.6/dist-packages/metaflow/task.py", line 198, in _clone_flow
2019-12-23 22:52:12.868 [1577141526437425/join/6 (pid 17256)] x = self.flow.__class__(use_cli=False)
2019-12-23 22:52:12.869 [1577141526437425/join/6 (pid 17256)] TypeError: __init__() got an unexpected keyword argument 'use_cli'
2019-12-23 22:52:12.869 [1577141526437425/join/6 (pid 17256)]
2019-12-23 22:52:12.870 [1577141526437425/join/6 (pid 17256)] Task failed.
```

**Comment by savingoyal** [comment]
Instead of declaring the ‘__init__’ method, you should use [Parameters](https://docs.metaflow.org/metaflow/basics#how-to-define-parameters-for-flows) to declare the values for `db_name` and `n_compounds`.

**Comment by mikejmills** [comment]
Excellent suggestion. So does one do all the init stuff in the start step? 

Sent via Superhuman ( https://sprh.mn/?vip=mikejmills@gmail.com )

**Comment by savingoyal** [comment]
Depends on what you want to initialize. You can declare all your parameters as top level variables and construct other Python objects out of them in any of the steps.
