### ISSUE TITLE
Tutorial 04-playlist-plus fails with AttributeError: Can't get attribute 'new_block'

### ISSUE THREAD

**Issue by mjanson** [Netflix/metaflow#733]
I am trying to ramp up on metaflow via the tutorial (thank you for sharing with the community!).

Made it through tutorials 01-03 fine, but have this issue when trying to run 04; not sure how to troubleshoot:

AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '/home/maj/anaconda3/envs/metaflow_PlayListFlow_linux-64_179c56284704ca8e53622f848a3df27cdd1f4327/lib/python3.7/site-packages/pandas/core/internals/blocks.py'>

All output:

$ python 04-playlist-plus/playlist.py --environment=conda run
Metaflow 2.3.6 executing PlayListFlow for user:maj
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
Bootstrapping conda environment...(this could take a few minutes)
2021-10-03 16:37:14.884 Workflow starting (run-id 1633304234877671):
2021-10-03 16:37:16.441 [1633304234877671/start/1 (pid 24405)] Task is starting.
2021-10-03 16:37:16.851 [1633304234877671/start/1 (pid 24405)] Using metadata provider: local@/home/maj/src/metaflow-tutorials
2021-10-03 16:37:16.853 [1633304234877671/start/1 (pid 24405)] Using analysis from 'Run('MovieStatsFlow/1633304170736085')'
2021-10-03 16:37:17.167 [1633304234877671/start/1 (pid 24405)] <flow PlayListFlow step start> failed:
2021-10-03 16:37:17.171 [1633304234877671/start/1 (pid 24405)] Internal error
2021-10-03 16:37:17.172 [1633304234877671/start/1 (pid 24405)] Traceback (most recent call last):
2021-10-03 16:37:17.172 [1633304234877671/start/1 (pid 24405)] File "/tmp/tmp0peibryj/metaflow/cli.py", line 1007, in main
2021-10-03 16:37:17.172 [1633304234877671/start/1 (pid 24405)] start(auto_envvar_prefix='METAFLOW', obj=state)
2021-10-03 16:37:17.173 [1633304234877671/start/1 (pid 24405)] File "/home/maj/anaconda3/envs/metaflow_PlayListFlow_linux-64_179c56284704ca8e53622f848a3df27cdd1f4327/lib/python3.7/site-packages/click/core.py", line 829, in __call__
2021-10-03 16:37:17.173 [1633304234877671/start/1 (pid 24405)] return self.main(args, kwargs)
2021-10-03 16:37:17.173 [1633304234877671/start/1 (pid 24405)] File "/home/maj/anaconda3/envs/metaflow_PlayListFlow_linux-64_179c56284704ca8e53622f848a3df27cdd1f4327/lib/python3.7/site-packages/click/core.py", line 782, in main
2021-10-03 16:37:17.173 [1633304234877671/start/1 (pid 24405)] rv = self.invoke(ctx)
2021-10-03 16:37:17.173 [1633304234877671/start/1 (pid 24405)] File "/home/maj/anaconda3/envs/metaflow_PlayListFlow_linux-64_179c56284704ca8e53622f848a3df27cdd1f4327/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
2021-10-03 16:37:17.173 [1633304234877671/start/1 (pid 24405)] return _process_result(sub_ctx.command.invoke(sub_ctx))
2021-10-03 16:37:17.173 [1633304234877671/start/1 (pid 24405)] File "/home/maj/anaconda3/envs/metaflow_PlayListFlow_linux-64_179c56284704ca8e53622f848a3df27cdd1f4327/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
2021-10-03 16:37:17.174 [1633304234877671/start/1 (pid 24405)] return ctx.invoke(self.callback, ctx.params)
2021-10-03 16:37:17.257 [1633304234877671/start/1 (pid 24405)] File "/home/maj/anaconda3/envs/metaflow_PlayListFlow_linux-64_179c56284704ca8e53622f848a3df27cdd1f4327/lib/python3.7/site-packages/click/core.py", line 610, in invoke
2021-10-03 16:37:17.257 [1633304234877671/start/1 (pid 24405)] return callback(args, kwargs)
2021-10-03 16:37:17.257 [1633304234877671/start/1 (pid 24405)] File "/home/maj/anaconda3/envs/metaflow_PlayListFlow_linux-64_179c56284704ca8e53622f848a3df27cdd1f4327/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
2021-10-03 16:37:17.258 [1633304234877671/start/1 (pid 24405)] return f(get_current_context(), args, kwargs)
2021-10-03 16:37:17.258 [1633304234877671/start/1 (pid 24405)] File "/tmp/tmp0peibryj/metaflow/cli.py", line 522, in step
2021-10-03 16:37:17.258 [1633304234877671/start/1 (pid 24405)] max_user_code_retries)
2021-10-03 16:37:17.258 [1633304234877671/start/1 (pid 24405)] File "/tmp/tmp0peibryj/metaflow/task.py", line 444, in run_step
2021-10-03 16:37:17.258 [1633304234877671/start/1 (pid 24405)] self._exec_step_function(step_func)
2021-10-03 16:37:17.259 [1633304234877671/start/1 (pid 24405)] File "/tmp/tmp0peibryj/metaflow/task.py", line 51, in _exec_step_function
2021-10-03 16:37:17.259 [1633304234877671/start/1 (pid 24405)] step_function()
2021-10-03 16:37:17.259 [1633304234877671/start/1 (pid 24405)] File "04-playlist-plus/playlist.py", line 71, in start
2021-10-03 16:37:17.259 [1633304234877671/start/1 (pid 24405)] self.dataframe = run['start'].task.data.dataframe
2021-10-03 16:37:17.259 [1633304234877671/start/1 (pid 24405)] File "/tmp/tmp0peibryj/metaflow/client/core.py", line 585, in __getattr__
2021-10-03 16:37:17.260 [1633304234877671/start/1 (pid 24405)] return self._artifacts[name].data
2021-10-03 16:37:17.260 [1633304234877671/start/1 (pid 24405)] File "/tmp/tmp0peibryj/metaflow/client/core.py", line 713, in data
2021-10-03 16:37:17.260 [1633304234877671/start/1 (pid 24405)] obj = pickle.load(f)
2021-10-03 16:37:17.260 [1633304234877671/start/1 (pid 24405)] AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '/home/maj/anaconda3/envs/metaflow_PlayListFlow_linux-64_179c56284704ca8e53622f848a3df27cdd1f4327/lib/python3.7/site-packages/pandas/core/internals/blocks.py'>
2021-10-03 16:37:17.260 [1633304234877671/start/1 (pid 24405)] 
2021-10-03 16:37:17.261 [1633304234877671/start/1 (pid 24405)] Task failed.
2021-10-03 16:37:17.262 Workflow failed.
2021-10-03 16:37:17.262 Terminating 0 active tasks...
2021-10-03 16:37:17.262 Flushing logs...
    Step failure:
    Step start (task-id 1) failed.

**Comment by russellbrooks** [comment]
I think this could be related to having incompatible versions of pandas when running the `02-statistics` tutorial compared to the `@conda` env of `04-playlist-plus` that has `pandas==0.24.2`.

In particular, there's some incompatible changes with pandas 1+ that could be breaking the pickle serialization.

Check if your local python env (that was used to run `02-statistics`) has pandas version 1+ and if so, try updating those conda decorators in `04-playlist-plus` to also have a pandas 1+ version. Alternatively, could also rerun the `02-statistics` flow with the older pandas version specified in `@conda` decorators too 🙂

**Comment by savingoyal** [comment]
Related - #707. We should retire these tutorials in favor of something that doesn't rely on pandas (or any other third party lib)
