### ISSUE TITLE
Flow failed due to missing dependency not referred

### ISSUE THREAD

**Issue by Jeffwan** [Netflix/metaflow#81]
I follow instruction and write big sum example. I use `python:latest` base image and this image doesn't have `numpy` library. I update to use @conda decorator at the start step. The problem is error occurs in the `end` step but it doesn't have any reference on `numpy`. 

python3 bigsum.py --environment=conda run

```
Metaflow 2.0.1 executing BigSum for user:shjiaxin
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint not found, so extra checks are disabled.
2019-12-27 14:56:26.136 Bootstrapping conda environment...(this could take a few minutes)
2019-12-27 14:56:28.141 Workflow starting (run-id 69):
2019-12-27 14:56:28.819 [69/start/254 (pid 35570)] Task is starting.
2019-12-27 14:56:32.973 [69/start/254 (pid 35570)] Task finished successfully.
2019-12-27 14:56:34.065 [69/end/255 (pid 35595)] Task is starting.
2019-12-27 14:56:36.110 [69/end/255 (pid 35595)] <flow BigSum step end> failed:
2019-12-27 14:56:36.114 [69/end/255 (pid 35595)] Internal error
2019-12-27 14:56:36.115 [69/end/255 (pid 35595)] Traceback (most recent call last):
2019-12-27 14:56:36.115 [69/end/255 (pid 35595)] File "/tmp/tmppku_v65f/metaflow/cli.py", line 853, in main
2019-12-27 14:56:36.115 [69/end/255 (pid 35595)] start(auto_envvar_prefix='METAFLOW', obj=state)
2019-12-27 14:56:36.115 [69/end/255 (pid 35595)] File "/Users/shjiaxin/miniconda/envs/metaflow_BigSum_osx-64_3d3fb5f54327676ef9bf2dfb5b4d0a3b8244dc31/lib/python3.7/site-packages/click/core.py", line 764, in __call__
2019-12-27 14:56:36.115 [69/end/255 (pid 35595)] return self.main(args, kwargs)
2019-12-27 14:56:36.116 [69/end/255 (pid 35595)] File "/Users/shjiaxin/miniconda/envs/metaflow_BigSum_osx-64_3d3fb5f54327676ef9bf2dfb5b4d0a3b8244dc31/lib/python3.7/site-packages/click/core.py", line 717, in main
2019-12-27 14:56:36.116 [69/end/255 (pid 35595)] rv = self.invoke(ctx)
2019-12-27 14:56:36.116 [69/end/255 (pid 35595)] File "/Users/shjiaxin/miniconda/envs/metaflow_BigSum_osx-64_3d3fb5f54327676ef9bf2dfb5b4d0a3b8244dc31/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
2019-12-27 14:56:36.116 [69/end/255 (pid 35595)] return _process_result(sub_ctx.command.invoke(sub_ctx))
2019-12-27 14:56:36.116 [69/end/255 (pid 35595)] File "/Users/shjiaxin/miniconda/envs/metaflow_BigSum_osx-64_3d3fb5f54327676ef9bf2dfb5b4d0a3b8244dc31/lib/python3.7/site-packages/click/core.py", line 956, in invoke
2019-12-27 14:56:36.116 [69/end/255 (pid 35595)] return ctx.invoke(self.callback, ctx.params)
2019-12-27 14:56:36.116 [69/end/255 (pid 35595)] File "/Users/shjiaxin/miniconda/envs/metaflow_BigSum_osx-64_3d3fb5f54327676ef9bf2dfb5b4d0a3b8244dc31/lib/python3.7/site-packages/click/core.py", line 555, in invoke
2019-12-27 14:56:36.117 [69/end/255 (pid 35595)] return callback(args, kwargs)
2019-12-27 14:56:36.117 [69/end/255 (pid 35595)] File "/Users/shjiaxin/miniconda/envs/metaflow_BigSum_osx-64_3d3fb5f54327676ef9bf2dfb5b4d0a3b8244dc31/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
2019-12-27 14:56:36.117 [69/end/255 (pid 35595)] return f(get_current_context().obj, args, kwargs)
2019-12-27 14:56:36.188 [69/end/255 (pid 35595)] File "/tmp/tmppku_v65f/metaflow/cli.py", line 430, in step
2019-12-27 14:56:36.190 [69/end/255 (pid 35595)] max_user_code_retries)
2019-12-27 14:56:36.191 [69/end/255 (pid 35595)] File "/tmp/tmppku_v65f/metaflow/task.py", line 390, in run_step
2019-12-27 14:56:36.191 [69/end/255 (pid 35595)] self._exec_step_function(step_func)
2019-12-27 14:56:36.191 [69/end/255 (pid 35595)] File "/tmp/tmppku_v65f/metaflow/task.py", line 47, in _exec_step_function
2019-12-27 14:56:36.191 [69/end/255 (pid 35595)] step_function()
2019-12-27 14:56:36.191 [69/end/255 (pid 35595)] File "bigsum.py", line 21, in end
2019-12-27 14:56:36.191 [69/end/255 (pid 35595)] print("The sum is %f." % self.sum)
2019-12-27 14:56:36.191 [69/end/255 (pid 35595)] File "/tmp/tmppku_v65f/metaflow/flowspec.py", line 122, in __getattr__
2019-12-27 14:56:36.191 [69/end/255 (pid 35595)] x = self._datastore[name]
2019-12-27 14:56:36.191 [69/end/255 (pid 35595)] File "/tmp/tmppku_v65f/metaflow/datastore/datastore.py", line 571, in __getitem__
2019-12-27 14:56:36.192 [69/end/255 (pid 35595)] return self._load_object(self.objects[var])
2019-12-27 14:56:36.192 [69/end/255 (pid 35595)] File "/tmp/tmppku_v65f/metaflow/datastore/datastore.py", line 453, in _load_object
2019-12-27 14:56:36.192 [69/end/255 (pid 35595)] return pickle.loads(blob)
2019-12-27 14:56:36.192 [69/end/255 (pid 35595)] ModuleNotFoundError: No module named 'numpy'
2019-12-27 14:56:36.192 [69/end/255 (pid 35595)]
2019-12-27 14:56:36.484 [69/end/255 (pid 35595)] Task failed.
2019-12-27 14:56:36.484 Workflow failed.
2019-12-27 14:56:36.484 Terminating 0 active tasks...
2019-12-27 14:56:36.484 Flushing logs...
    Step failure:
    Step end (task-id 255) failed.

```

metaflow code
```
from metaflow import FlowSpec, step, resources, batch, conda

class BigSum(FlowSpec):

    @resources(memory=4500, cpu=1)
    @batch
    @conda(libraries={'numpy':'1.17.3'})
    @step
    def start(self):
        import numpy
        import time
        big_matrix = numpy.random.ranf((10000, 10000))
        t = time.time()
        self.sum = numpy.sum(big_matrix)
        self.took = time.time() - t
        self.next(self.end)

    @batch
    @step
    def end(self):
        print("The sum is %f." % self.sum)
        print("Computing it took %dms." % (self.took * 1000))

if __name__ == '__main__':
    BigSum()

```

**Comment by savingoyal** [comment]
`self.sum` has a dependency on numpy since it can be an `ndarray`. A quick check would be to comment out the first print statement in the `end` step and reexecute.

**Comment by vfrank66** [comment]
@savingoyal this was the solution for me, thank you!
