### ISSUE TITLE
Issues Running Example Code to Create Step Function Flow from Metaflow

### ISSUE THREAD

**Issue by whitehatbuds** [Netflix/metaflow#820]
Hello,

I need some help figuring out what the error message means, I was trying to run this example code from:
[https://docs.metaflow.org/going-to-production-with-metaflow/scheduling-metaflow-flows#pushing-a-flow-to-production](url)
I ran the exact code with the command: 
`python parameter_flow.py --datastore=s3 --with retry step-functions create` 
I added the --datastore flag that wasn't in the docs because metaflow prompted me for it with an error.

I set the `METAFLOW_DATASTORE_SYSROOT_S3` env variable too.

I'm running 
python version: `3.9.7`
metaflow version: `2.4.0`
botocore: `1.21.59`

I got this error afterwards:

Internal error
Traceback (most recent call last):
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/metaflow/cli.py", line 971, in main
    start(auto_envvar_prefix='METAFLOW', obj=state)
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(args, kwargs)
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(args, kwargs)
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, args, kwargs)
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/metaflow/plugins/aws/step_functions/step_functions_cli.py", line 118, in create
    flow = make_flow(obj,
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/metaflow/plugins/aws/step_functions/step_functions_cli.py", line 239, in make_flow
    return StepFunctions(name,
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/metaflow/plugins/aws/step_functions/step_functions.py", line 69, in __init__
    self._workflow = self._compile()
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/metaflow/plugins/aws/step_functions/step_functions.py", line 292, in _compile
    return _visit(self.graph['start'], workflow)
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/metaflow/plugins/aws/step_functions/step_functions.py", line 216, in _visit
    .batch(self._batch(node)) \
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/metaflow/plugins/aws/step_functions/step_functions.py", line 593, in _batch
    return Batch(self.metadata, self.environment) \
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/metaflow/plugins/aws/batch/batch.py", line 179, in create_job
    job \
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/metaflow/plugins/aws/batch/batch_client.py", line 238, in job_def
    self._register_job_definition(image,
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/metaflow/plugins/aws/batch/batch_client.py", line 114, in _register_job_definition
    response = self._client.describe_job_queues(jobQueues=[job_queue])
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/botocore/client.py", line 680, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/botocore/client.py", line 728, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/Users/kahtan/miniconda3/opt/envs/metaflow39/lib/python3.9/site-packages/botocore/validate.py", line 360, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter jobQueues[0], value: None, type: <class 'NoneType'>, valid types: <class 'str'>

**Comment by blackrez** [comment]
Hello, I have the same issue here but with python3.11.

```
(base) ➜  metaflow-demo python parameter_flow.py --datastore=s3 step-functions create
Metaflow 2.10.2 executing ParameterFlow for user:nabil_servais
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint not found, so extra checks are disabled.
Deploying ParameterFlow to AWS Step Functions...
It seems this is the first time you are deploying ParameterFlow to AWS Step Functions.

A new production token generated.

The namespace of this production flow is
    production:parameterflow-0-gtqo
To analyze results of this production flow add this line in your notebooks:
    namespace("production:parameterflow-0-gtqo")
If you want to authorize other people to deploy new versions of this flow to AWS Step Functions, they need to call
    step-functions create --authorize parameterflow-0-gtqo
when deploying this flow to AWS Step Functions for the first time.
See "Organizing Results" at https://docs.metaflow.org/ for more information about production tokens.

    Internal error
Traceback (most recent call last):
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/cli.py", line 1172, in main
    start(auto_envvar_prefix="METAFLOW", obj=state)
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
    return self.main(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
    return callback(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/_vendor/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/plugins/aws/step_functions/step_functions_cli.py", line 156, in create
    flow = make_flow(
           ^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/plugins/aws/step_functions/step_functions_cli.py", line 291, in make_flow
    return StepFunctions(
           ^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/plugins/aws/step_functions/step_functions.py", line 80, in __init__
    self._workflow = self._compile()
                     ^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/plugins/aws/step_functions/step_functions.py", line 347, in _compile
    return _visit(self.graph["start"], workflow)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/plugins/aws/step_functions/step_functions.py", line 270, in _visit
    .batch(self._batch(node))
           ^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/plugins/aws/step_functions/step_functions.py", line 688, in _batch
    .create_job(
     ^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/plugins/aws/batch/batch.py", line 221, in create_job
    .job_def(
     ^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/plugins/aws/batch/batch_client.py", line 382, in job_def
    self.payload["jobDefinition"] = self._register_job_definition(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/metaflow/plugins/aws/batch/batch_client.py", line 168, in _register_job_definition
    response = self._client.describe_job_queues(jobQueues=[job_queue])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/botocore/client.py", line 534, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/botocore/client.py", line 935, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/botocore/client.py", line 1003, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabil_servais/miniconda3/lib/python3.11/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter jobQueues[0], value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

**Comment by exequiellobon** [comment]
Have anybody solved this issue?

**Comment by savingoyal** [comment]
@exequiellobon you might have an old version of boto3. can you upgrade boto3 and try again?

**Comment by exequiellobon** [comment]
Yes, I've updated, my problem was solved setting metaflow configuration for AWS with `metaflow configure aws` and setting role policy.
