### ISSUE TITLE
S3 client should not expect current directory to be writeable

### ISSUE THREAD

**Issue by oavdeev** [Netflix/metaflow#854]
By default it tries to download artifacts to CWD, which is not always writeable. To reproduce, run some flows, cd to a read-only directory and run something like 

```python
list(metaflow.Flow('HelloFlow').runs())[0].finished
```

**Comment by emocibob** [comment]
Here's the original post from Slack that was the motivation for creating this issue:

> Hi, I’m trying to list flows and runs in AWS Lambda. I bundled the metaflow Python package with its dependencies in the Lambda.
> I dynamically create a Metaflow profile with the following vars:
> 
> ```
> "METAFLOW_DEFAULT_DATASTORE": "s3",
> "METAFLOW_DATASTORE_SYSROOT_S3"
> "METAFLOW_DATATOOLS_SYSROOT_S3"
> "METAFLOW_BATCH_JOB_QUEUE"
> "METAFLOW_ECS_S3_ACCESS_IAM_ROLE"
> "METAFLOW_DEFAULT_METADATA": "service",
> "METADATA_SERVICE_URL"
> "METAFLOW_SERVICE_URL"
> "METAFLOW_CONDA_PACKAGE_S3ROOT"
> "METAFLOW_SERVICE_AUTH_KEY"
> ```
> 
> I can list the flows but when I try to list the runs I get the following error:
> 
> ```
> Flow('CheckIp') has 8 run(s)
> [ERROR] OSError: [Errno 30] Read-only file system: '/var/task/metaflow.s3.nk_lfgr1'
> Traceback (most recent call last):
>   ...
>   File "/var/task/main.py", line 361, in print_metaflow_flows_info
>     "| Finished:", run.finished,
>   File "/var/task/packages/metaflow/client/core.py", line 1592, in finished
>     return end.finished
>   File "/var/task/packages/metaflow/client/core.py", line 1051, in finished
>     return self["_task_ok"].data
>   File "/var/task/packages/metaflow/client/core.py", line 790, in data
>     return filecache.get_artifact_by_location(
>   File "/var/task/packages/metaflow/client/filecache.py", line 191, in get_artifact_by_location
>     return self.get_artifact(
>   File "/var/task/packages/metaflow/client/filecache.py", line 206, in get_artifact
>     _, obj = next(
>   File "/var/task/packages/metaflow/datastore/task_datastore.py", line 360, in load_artifacts
>     for name, (_, blob) in zip(names, self._ca_store.load_blobs(to_load)):
>   File "/var/task/packages/metaflow/datastore/content_addressed_store.py", line 135, in load_blobs
>     with self._storage_impl.load_bytes([p for _, p in load_paths]) as loaded:
>   File "/var/task/packages/metaflow/datastore/s3_storage.py", line 121, in load_bytes
>     s3 = S3(
>   File "/var/task/packages/metaflow/datatools/s3.py", line 344, in __init__
>     self._tmpdir = mkdtemp(dir=tmproot, prefix="metaflow.s3.")
>   File "/var/lang/lib/python3.9/tempfile.py", line 363, in mkdtemp
>     _os.mkdir(file, 0o700)END RequestId: 3c1241d2-5350-446a-81cb-fb1d3db597b7
> ```
> 
> The error states that an artifact is being created outside of /tmp (the only writable dir).
> Is there a [config var](https://github.com/Netflix/metaflow/blob/0f09a1dd736b30e433a65362290690deeb0d679d/metaflow/metaflow_config.py) I can use to override the default tmproot in the [S3 client](https://github.com/Netflix/metaflow/blob/aa51c0b11e47213e5e27852a2f0fbb9fd631e420/metaflow/datatools/s3.py#L344)?

Workaround:

> one workaround would be to `os.chdir()` to a writeable directory before calling this

**Comment by vedantRaikar** [comment]
**Proposed fix: fall back to a writable temp dir when the configured artifact localroot is read-only**

I am a new contributor and would like to take a shot at this one. Here is my proposed approach, happy to adjust based on feedback.

**Reproduction**
```
mkdir -m 0500 /tmp/mf-readonly && cd /tmp/mf-readonly
python -c "from metaflow.plugins.datatools.s3.s3 import S3; S3(tmproot='.')"
# PermissionError: [Errno 13]
```
This is the same code path that `Run('Flow/...').finished` hits when the current directory is read-only.

**Root cause**
- `ARTIFACT_LOCALROOT` defaults to `os.getcwd()` at import time (metaflow_config.py:241); `TEMPDIR` defaults to `.` for the raw S3 datatools client.
- `S3.__init__` eagerly creates a scratch dir via `mkdtemp(dir=self._tmproot, ...)` (s3.py:590), which raises `PermissionError` when that root is not writable.
- The same pattern exists in the Azure and GS datastores (azure_storage.py:344/378, gs_storage.py:220/251).

**Proposed change (minimal)**
Add a helper, `safe_mkdtemp(dir, prefix)` in metaflow/util.py, that tries the requested directory and, on `OSError`, falls back to `tempfile.mkdtemp()` (system temp) with a warning so the fallback is not silent. Use it at the mkdtemp sites in s3.py, azure_storage.py, and gs_storage.py. Behavior is unchanged when the configured root works, so existing setups are not affected.

**Tests**
- Unit tests for the helper: creates under the requested root when writable, falls back to system temp when the root is read-only (tmp_path + chmod 0o500).
- An S3-level test using a dummy external client, gated on boto3 availability.

If this sounds right I will open a PR with tests that fail before and pass after.
