### ISSUE TITLE
Dependency Error When using `--with kubernetees` flag

### ISSUE THREAD

**Issue by hamelsmu** [Netflix/metaflow#931]
> python flow.py --environment=conda resume train_model --with kubernetes

```
Metaflow 2.5.0 executing NBFlow for user:hamel
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
Bootstrapping conda environment...(this could take a few minutes)
2022-01-27 11:56:49.338 Gathering required information to resume run (this may take a bit of time)...
2022-01-27 11:57:04.874 Workflow starting (run-id 6106):
2022-01-27 11:57:05.234 [6106/start/131068] Cloning results of a previously run task 6103/start/131059
2022-01-27 11:57:07.289 [6106/train_model/131069 (pid 19164)] Task is starting.
2022-01-27 11:57:08.090 [6106/train_model/131069 (pid 19164)] Traceback (most recent call last):
2022-01-27 11:57:08.173 [6106/train_model/131069 (pid 19164)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/metaflow/plugins/aws/eks/kubernetes_client.py", line 67, in __init__
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] from kubernetes import client, config
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] ModuleNotFoundError: No module named 'kubernetes'
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)]
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] During handling of the above exception, another exception occurred:
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)]
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] Traceback (most recent call last):
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/metaflow/plugins/aws/eks/kubernetes_cli.py", line 196, in step
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] kubernetes.launch_job(
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/metaflow/plugins/aws/eks/kubernetes.py", line 173, in launch_job
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] self._job = self.create_job(**kwargs).execute()
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/metaflow/plugins/aws/eks/kubernetes.py", line 217, in create_job
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] KubernetesClient()
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/metaflow/plugins/aws/eks/kubernetes_client.py", line 69, in __init__
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] raise MetaflowException(
2022-01-27 11:57:08.174 [6106/train_model/131069 (pid 19164)] metaflow.exception.MetaflowException: Could not import module 'kubernetes'. Install kubernetes Python package (https://pypi.org/project/kubernetes/) first.
2022-01-27 11:57:08.257 [6106/train_model/131069 (pid 19164)] Task failed.
2022-01-27 11:57:08.436 This failed task will not be retried.
    Internal error:
    The end step was not successful by the end of flow.
```

cc: @oavdeev

**Comment by hamelsmu** [comment]
I tried installing `kubernetes` and then got this error:

```
 python flow.py --environment=conda --package-suffixes=".ipynb" resume train_model --with kubernetes
Metaflow 2.5.0 executing NBFlow for user:hamel
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
Bootstrapping conda environment...(this could take a few minutes)
2022-01-27 12:19:17.783 Gathering required information to resume run (this may take a bit of time)...
2022-01-27 12:19:32.524 Workflow starting (run-id 6112):
2022-01-27 12:19:32.878 [6112/start/131090] Cloning results of a previously run task 6103/start/131059
2022-01-27 12:19:35.020 [6112/train_model/131091 (pid 20646)] Task is starting.
2022-01-27 12:19:36.691 [6112/train_model/131091 (pid 20646)] [ec5fb667-9dc1-41db-8fef-ef237ce25dfa] Task is starting (Status Job:Active Pod:Pending Container:Waiting [ContainerCreating])...
2022-01-27 12:19:38.174 [6112/train_model/131091 (pid 20646)] [ec5fb667-9dc1-41db-8fef-ef237ce25dfa] Task is starting (Status Job:Active Pod:Running Container:Running)...
2022-01-27 12:19:37.567 [6112/train_model/131091 (pid 20646)] [ec5fb667-9dc1-41db-8fef-ef237ce25dfa] Setting up task environment.
2022-01-27 12:19:47.945 [6112/train_model/131091 (pid 20646)] [ec5fb667-9dc1-41db-8fef-ef237ce25dfa] Downloading code package...
2022-01-27 12:19:48.798 [6112/train_model/131091 (pid 20646)] [ec5fb667-9dc1-41db-8fef-ef237ce25dfa] Code package downloaded.
2022-01-27 12:19:48.920 [6112/train_model/131091 (pid 20646)] [ec5fb667-9dc1-41db-8fef-ef237ce25dfa] Task is starting.
2022-01-27 12:19:49.463 [6112/train_model/131091 (pid 20646)] [ec5fb667-9dc1-41db-8fef-ef237ce25dfa] Bootstrapping environment...
2022-01-27 12:21:15.854 [6112/train_model/131091 (pid 20646)] [ec5fb667-9dc1-41db-8fef-ef237ce25dfa] Environment bootstrapped.
2022-01-27 12:28:14.663 [6112/train_model/131091 (pid 20646)] [ec5fb667-9dc1-41db-8fef-ef237ce25dfa] Task finished with exit code 0.
2022-01-27 12:28:15.297 [6112/train_model/131091 (pid 20646)] Task finished successfully.
2022-01-27 12:28:16.512 [6112/evaluate/131094 (pid 20781)] Task is starting.
2022-01-27 12:28:17.751 [6112/evaluate/131094 (pid 20781)] ERROR:root:exec: process returned 255. cannot import name 'get_event_loop' from 'prompt_toolkit.eventloop' (/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/prompt_toolkit/eventloop/__init__.py)
2022-01-27 12:28:17.800 [6112/evaluate/131094 (pid 20781)] Traceback (most recent call last):
2022-01-27 12:28:17.800 [6112/evaluate/131094 (pid 20781)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/metaflow/plugins/aws/eks/kubernetes_client.py", line 299, in execute
2022-01-27 12:28:17.800 [6112/evaluate/131094 (pid 20781)] client.BatchV1Api()
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/kubernetes/client/api/batch_v1_api.py", line 204, in create_namespaced_job
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] return self.create_namespaced_job_with_http_info(namespace, body, **kwargs)  # noqa: E501
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/kubernetes/client/api/batch_v1_api.py", line 299, in create_namespaced_job_with_http_info
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] return self.api_client.call_api(
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] return self.__call_api(resource_path, method,
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] response_data = self.request(
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 391, in request
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] return self.rest_client.POST(url,
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/kubernetes/client/rest.py", line 275, in POST
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] return self.request("POST", url,
2022-01-27 12:28:17.801 [6112/evaluate/131094 (pid 20781)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/kubernetes/client/rest.py", line 234, in request
2022-01-27 12:28:17.802 [6112/evaluate/131094 (pid 20781)] raise ApiException(http_resp=r)
2022-01-27 12:28:17.802 [6112/evaluate/131094 (pid 20781)] kubernetes.client.exceptions.ApiException: (403)
2022-01-27 12:28:17.907 [6112/evaluate/131094 (pid 20781)] Reason: Forbidden
2022-01-27 12:28:17.907 [6112/evaluate/131094 (pid 20781)] HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ab359348-652f-43c1-8411-01bd3c3cc0de', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '8f2995f1-65cc-4419-be38-77614ed4b7c0', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'bd32a966-598c-4781-a06b-33849fc2f19c', 'Date': 'Thu, 27 Jan 2022 20:28:17 GMT', 'Content-Length': '296'})
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"jobs.batch is forbidden: User \"system:anonymous\" cannot create resource \"jobs\" in API group \"batch\" in the namespace \"metaflow-jobs\"","reason":"Forbidden","details":{"group":"batch","kind":"jobs"},"code":403}
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)]
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)]
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)]
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] During handling of the above exception, another exception occurred:
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)]
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] Traceback (most recent call last):
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/metaflow/plugins/aws/eks/kubernetes_cli.py", line 196, in step
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] kubernetes.launch_job(
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/metaflow/plugins/aws/eks/kubernetes.py", line 173, in launch_job
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] self._job = self.create_job(**kwargs).execute()
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] File "/Users/hamel/opt/anaconda3/lib/python3.9/site-packages/metaflow/plugins/aws/eks/kubernetes_client.py", line 312, in execute
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] raise KubernetesJobException(
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] metaflow.plugins.aws.eks.kubernetes_client.KubernetesJobException: Unable to launch Kubernetes job.
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] (403)
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] Reason: Forbidden
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ab359348-652f-43c1-8411-01bd3c3cc0de', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '8f2995f1-65cc-4419-be38-77614ed4b7c0', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'bd32a966-598c-4781-a06b-33849fc2f19c', 'Date': 'Thu, 27 Jan 2022 20:28:17 GMT', 'Content-Length': '296'})
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)] HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"jobs.batch is forbidden: User \"system:anonymous\" cannot create resource \"jobs\" in API group \"batch\" in the namespace \"metaflow-jobs\"","reason":"Forbidden","details":{"group":"batch","kind":"jobs"},"code":403}
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)]
2022-01-27 12:28:17.908 [6112/evaluate/131094 (pid 20781)]
2022-01-27 12:28:17.993 [6112/evaluate/131094 (pid 20781)] Task failed.
2022-01-27 12:28:18.106 This failed task will not be retried.
    Internal error:
    The end step was not successful by the end of flow.
```
