### ISSUE TITLE
Metaflow-UI DAG Error

### ISSUE THREAD

**Issue by AbdAlRahman-Odeh-99** [Netflix/metaflow#950]
Hello
I am trying to view the DAG of my workflow via the UI. but it gives me the following error.
`TypeError: expected str, bytes or os.PathLike object, not NoneType`
I am running the metaflow locally on ubuntu. The full traceback as follows.

> Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/services/ui_backend_service/data/cache/client/cache_server.py", line 302, in <module>
    cli(auto_envvar_prefix='MFCACHE')
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/services/ui_backend_service/data/cache/client/cache_server.py", line 298, in cli
    Scheduler(store, max_actions).loop()
  File "/root/services/ui_backend_service/data/cache/client/cache_server.py", line 199, in __init__
    maxtasksperchild=512,  # Recycle each worker once 512 tasks have been completed
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/root/services/ui_backend_service/data/cache/client/cache_worker.py", line 29, in execute_action
    execute(tempdir, action_cls, request)
  File "/root/services/ui_backend_service/data/cache/client/cache_worker.py", line 56, in execute
    invalidate_cache=req.get('invalidate_cache', False))
  File "/root/services/ui_backend_service/data/cache/generate_dag_action.py", line 97, in execute
    results[result_key] = json.dumps(dag)
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/services/ui_backend_service/data/cache/utils.py", line 130, in streamed_errors
    get_traceback_str()
  File "/root/services/ui_backend_service/data/cache/utils.py", line 124, in streamed_errors
    yield
  File "/root/services/ui_backend_service/data/cache/generate_dag_action.py", line 93, in execute
    dag = DataArtifact("{}/_graph_info".format(param_step.task.pathspec)).data
  File "/usr/local/lib/python3.7/site-packages/metaflow/client/core.py", line 827, in data
    return filecache.get_artifact(ds_type, location[6:], meta, *components)
  File "/usr/local/lib/python3.7/site-packages/metaflow/client/filecache.py", line 215, in get_artifact
    [name],
  File "/usr/local/lib/python3.7/site-packages/metaflow/datastore/task_datastore.py", line 361, in load_artifacts
    for (key, blob) in self._ca_store.load_blobs(to_load.keys()):
  File "/usr/local/lib/python3.7/site-packages/metaflow/datastore/content_addressed_store.py", line 140, in load_blobs
    with open(file_path, "rb") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by AbdAlRahman-Odeh-99** [comment]
It is executed uaing Metaflow 2.5.0. All other functionalities of the UI work well except for the DAG one.

**Comment by savingoyal** [comment]
Would you mind continuing the conversation at chat.metaflow.org so that we can debug live?

**Comment by AbdAlRahman-Odeh-99** [comment]
@savingoyal sure will do. I have joined it, on what channel shall we communicate?

**Comment by savingoyal** [comment]
#ask-metaflow channel would be most appropriate.

**Comment by DonIvanCorleone** [comment]
Sorry for opening this issue again, but currently I have the exact same error message. 
Would it be possible to document the solution here as well?

Many thanks.
Cheers

**Comment by AbdAlRahman-Odeh-99** [comment]
The issue was that I had my data locally. For Metaflow-UI to work, the data must be uploaded to the cloud such as S3. An alternative solution for local data is to use the @card tag.
Cheers

**Comment by DonIvanCorleone** [comment]
Thanks. Will try your suggestion.
Cheers

Am 27. Juli 2022 21:16:23 schrieb AbdAlRahman-Odeh-99
***@***.***>:

**Comment by truong04** [comment]
> Thanks. Will try your suggestion.
> Cheers
> 
> Am 27. Juli 2022 21:16:23 schrieb AbdAlRahman-Odeh-99
> ***@***.***>:
> […](#)

Sorry but did you fix it
