### ISSUE TITLE
update dependencies to require click-7.0

### ISSUE THREAD

**Issue by jdprusa** [Netflix/metaflow#97]
`pip install metaflow` on a sagemaker notebook instance followed by  `metaflow tutorials pull`resulted in the following error:

```
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/bin/metaflow", line 7, in <module>
    from metaflow.main_cli import main
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/metaflow/main_cli.py", line 243, in <module>
    @click.argument('episode', autocompletion=autocomplete_episodes)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/click/decorators.py", line 151, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/click/core.py", line 1699, in __init__
    Parameter.__init__(self, param_decls, required=required, **attrs)
TypeError: __init__() got an unexpected keyword argument 'autocompletion'
```

Metaflow requires click-v7.0, running with click-v6.7 See: https://github.com/pallets/click/issues/966
`pip install metaflow` should check versions of dependencies and ensure they are up to date.

**Comment by ddysher** [comment]
+1  manually upgrade click solves the problem
