### ISSUE TITLE
metaflow CLI doesn't work with most recent versions of `click` (`click>=8.0`)

### ISSUE THREAD

**Issue by peterwilton-ttam** [Netflix/metaflow#996]
Since `click==8.0` ([changelog](https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0-0)), click's `autocompletion` argument has been renamed to `shell_complete`. This breaks the Metaflow CLI:

``` bash
$ metaflow configure show
Traceback (most recent call last):
  File "/usr/local/bin/metaflow", line 5, in <module>
    from metaflow.main_cli import main
  File "/usr/local/lib/python3.8/site-packages/metaflow/main_cli.py", line 245, in <module>
    def info(episode):
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 287, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 2947, in __init__
    super().__init__(param_decls, required=required, **attrs)
TypeError: __init__() got an unexpected keyword argument 'autocompletion' 

$ python -c "import click; print(click.__version__)"
8.1.1
```

I see that Metaflow is vendoring `click==7.1.2`, but the Metaflow CLI doesn't seem to be using the vendored version of click.

**Comment by savingoyal** [comment]
What is the version of Metaflow that you are using?

**Comment by savingoyal** [comment]
No worries - glad we could resolve this.
